-- =========================================================
-- ABC TRAVELS - COMPLETE SUPABASE SETUP & SEED DATA
-- Copy and paste this entire script into your Supabase SQL Editor and click 'Run'.
-- =========================================================

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Destinations Table
CREATE TABLE IF NOT EXISTS public.destinations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    slug VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    region VARCHAR(100) NOT NULL,
    tagline VARCHAR(255),
    hero_image TEXT NOT NULL,
    description TEXT NOT NULL,
    best_time_to_visit VARCHAR(255),
    weather_info VARCHAR(255),
    ideal_duration VARCHAR(100),
    highlights JSONB DEFAULT '[]'::jsonb,
    gallery JSONB DEFAULT '[]'::jsonb,
    is_featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tours / Packages Table
CREATE TABLE IF NOT EXISTS public.tours (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    slug VARCHAR(255) UNIQUE NOT NULL,
    destination_id UUID REFERENCES public.destinations(id) ON DELETE SET NULL,
    destination_name VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(500),
    duration_days INT NOT NULL,
    duration_nights INT NOT NULL,
    price_usd NUMERIC(10, 2) NOT NULL,
    price_inr NUMERIC(12, 2) NOT NULL,
    activity_level VARCHAR(50) NOT NULL,
    travel_style VARCHAR(100) NOT NULL,
    group_type VARCHAR(100) DEFAULT 'Private Tailormade',
    is_featured BOOLEAN DEFAULT false,
    hero_image TEXT NOT NULL,
    gallery JSONB DEFAULT '[]'::jsonb,
    overview TEXT NOT NULL,
    highlights JSONB DEFAULT '[]'::jsonb,
    itinerary JSONB DEFAULT '[]'::jsonb,
    inclusions JSONB DEFAULT '[]'::jsonb,
    exclusions JSONB DEFAULT '[]'::jsonb,
    accommodations JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Inquiries / Leads Table
CREATE TABLE IF NOT EXISTS public.inquiries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tour_id UUID REFERENCES public.tours(id) ON DELETE SET NULL,
    tour_title VARCHAR(255),
    traveler_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    country VARCHAR(100) NOT NULL,
    departure_date DATE,
    duration_days INT,
    guests_count INT DEFAULT 2,
    budget_tier VARCHAR(100),
    travel_styles JSONB DEFAULT '[]'::jsonb,
    special_requests TEXT,
    status VARCHAR(50) DEFAULT 'NEW',
    admin_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Reviews / Testimonials Table
CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tour_id UUID REFERENCES public.tours(id) ON DELETE SET NULL,
    tour_title VARCHAR(255),
    traveler_name VARCHAR(255) NOT NULL,
    traveler_country VARCHAR(100) NOT NULL,
    traveler_avatar TEXT,
    rating INT DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
    title VARCHAR(255),
    comment TEXT NOT NULL,
    trip_date VARCHAR(100),
    is_approved BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.destinations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tours ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Public can read destinations, tours, and reviews
CREATE POLICY "Allow public read destinations" ON public.destinations FOR SELECT USING (true);
CREATE POLICY "Allow public read tours" ON public.tours FOR SELECT USING (true);
CREATE POLICY "Allow public read reviews" ON public.reviews FOR SELECT USING (true);

-- Public can submit new leads / inquiries
CREATE POLICY "Allow public insert inquiries" ON public.inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read own or all inquiries" ON public.inquiries FOR SELECT USING (true);
CREATE POLICY "Allow update inquiries" ON public.inquiries FOR UPDATE USING (true);

-- =========================================================
-- SEED DATA: DESTINATIONS
-- 2. Insert 12 Sovereign Destinations First
INSERT INTO public.destinations (slug, name, region, tagline, hero_image, description, best_time_to_visit, weather_info, ideal_duration, highlights, gallery, is_featured)
VALUES
(
    'rajasthan',
    'Rajasthan',
    'North India',
    $$Fortress Citadels, Lake Palaces & Living Royal Heritage$$,
    '/images/destinations/rajasthan/hero.jpg',
    $$Rajasthan endures as the ultimate sovereign theatre of the Indian subcontinent. Across the arid folds of the Aravalli hills and into the boundless sea of the Thar Desert, martial pride, astral philosophy, and architectural extravagance converge into a living civilization. This is a landscape where sandstone ramparts emerge organically from granite ridges, crowned by monumental battlements that have withstood centuries of siege warfare and dynastic triumph.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$20°C - 28°C Day / 8°C - 14°C Night$$,
    $$8 to 12 Days$$,
    $$["Private Access to the Chandra Mahal Suites, Jaipur: Curator-escorted, after-hours exploration of the private royal residential quarters of the Jaipur City Palace,...","Sunset Royal Barge Cruise on Lake Pichola, Udaipur: Private navigation of Lake Pichola aboard an antique Mewar royal barge adorned with velvet bolsters and ceremo...","Private Sundowner atop the Ramparts of Mehrangarh Fort, Jodhpur: Exclusive twilight reception on the highest battlements of Mehrangarh after public gates close, accompanied by...","Architectural Pilgrimage to the Marble Sanctum of Ranakpur: Early morning private visit to the 15th-century Adinatha Jain Temple, guided by an epigraphist and scholar of ...","Royal Polo Masterclass & Chukker Reception, Jaipur: Private morning riding and stick-and-ball instruction at the Jaipur Polo Club or private royal equestrian grou..."]$$::jsonb,
    $$["/images/destinations/rajasthan/hero.jpg","/images/destinations/rajasthan/jaipur-hawa-mahal.jpg","/images/destinations/rajasthan/udaipur-lake-palace.jpg","/images/destinations/rajasthan/jodhpur-blue-city.jpg","/images/destinations/rajasthan/ranakpur-marble-temple.jpg","/images/destinations/rajasthan/lake-palace-royal-barge.jpg"]$$::jsonb,
    true
  ),
(
    'kerala',
    'Kerala & The Spice Coast',
    'South India',
    $$Spice Plantations, Backwater Canals & Classical Ayurveda$$,
    '/images/destinations/kerala/hero.jpg',
    $$Kerala exists in a state of aquatic grace. Framed by the mist-shrouded biodiversity of the Western Ghats to the east and the warm expanse of the Arabian Sea to the west, this narrow strip of tropical land is defined by water: meandering inland canals, vast brackish lagoons, and monsoon-fed mountain streams. Here, maritime breezes carry the ancient scent of green cardamom pods, crushed nutmeg, and drying black pepper.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$23°C - 30°C Coastal / 12°C - 22°C Munnar Hills$$,
    $$7 to 10 Days$$,
    $$["Private Kettuvallam Houseboat Navigation through Secluded Canals: Tailored overnight journey aboard a handcrafted single-bedroom luxury kettuvallam through the quiet interior b...","Private Kathakali Green-Room Ritual & Chamber Performance: Exclusive access to the sacred three-hour *Chutti* mineral makeup application ritual, observing master actors ...","Botanical Spice Foraging & Estate Masterclass in Munnar: Private walking exploration through a heritage spice and cardamom plantation in the Western Ghats with a senio...","Physician-Guided Classical Ayurvedic Wellness Sanctuary, Kumarakom: In-depth personal consultation with a senior Vaidya (Ayurvedic doctor) at Kumarakom Lake Resort, followed by c...","Private Historic Twilight Cruise of Cochin Harbor: Private wooden motor yacht charter past the iconic Chinese fishing nets, Bolgatty Palace, and Willingdon Islan..."]$$::jsonb,
    $$["/images/destinations/kerala/hero.jpg","/images/destinations/kerala/alleppey-houseboat.jpg","/images/destinations/kerala/munnar-tea-plantations.jpg","/images/destinations/kerala/kochi-chinese-nets.jpg","/images/destinations/kerala/thekkady-spice-plantation.jpg","/images/destinations/kerala/hotel-kumarakom-lake-resort.jpg"]$$::jsonb,
    true
  ),
(
    'ladakh',
    'Ladakh & High Himalayas',
    'Himalayas & Ladakh',
    $$High-Altitude Monasteries, Glacial Passes & Silk Road Valleys$$,
    '/images/destinations/ladakh/hero.jpg',
    $$Ladakh unfolds at the roof of the world. Straddling the high plateau between the Karakoram and Great Himalaya mountain ranges at altitudes exceeding 11,000 feet, this is a trans-Himalayan desert of monumental proportions. The landscape is stripped of all non-essentials: bare, mineral-rich mountains of violet, slate, and ochre rise sharply toward an indigo sky so thin and clear that the sun illuminates every geological fault line with absolute sharpness.$$,
    $$May to September (Himalayan Summer / Optimal Season - prime touring climate)$$,
    $$15°C - 25°C Day / 5°C - 10°C Night$$,
    $$8 to 11 Days$$,
    $$["Pre-Dawn Monastic Puja & Butter Lamp Offering, Thiksey Monastery: Private dawn ascent to the rooftop of Thiksey Gompa before public sunrise, participating in the monks' morning...","Private Audience & Meditation with a Senior Rinpoche, Hemis: Exclusive private consultation and philosophical discourse on mindfulness and Vajrayana cosmology with an inca...","Expedition across Khardung La in Luxury Heated 4x4s: Private transit of the 17,582-foot pass in customized, oxygen-equipped luxury 4x4 vehicles (Toyota Land Cruise...","Astronomical Stargazing & Glamping by Pangong Tso: Exclusive overnight stay in heated luxury yurt domes along the secluded shoreline of Pangong Tso, featuring hi...","Two-Humped Bactrian Camel Caravan across Hunder Sand Dunes: Private twilight camel trek across the white dunes of Nubra Valley, followed by an open-air sundowner campfire..."]$$::jsonb,
    $$["/images/destinations/ladakh/hero.jpg","/images/destinations/ladakh/thiksey-monastery.jpg","/images/destinations/ladakh/pangong-lake-azure.jpg","/images/destinations/ladakh/hunder-bactrian-camels.jpg","/images/destinations/ladakh/khardungla-pass.jpg","/images/destinations/ladakh/leh-palace-old-town.jpg"]$$::jsonb,
    true
  ),
(
    'varanasi',
    'Varanasi & Sacred Ganges',
    'North India',
    $$Riverfront Rituals, Classical Heritage & Sacred Antiquity$$,
    '/images/destinations/varanasi/hero.jpg',
    $$Varanasi does not belong entirely to the linear flow of modern time. Regarded by historians as one of the world's oldest continuously inhabited cities, and revered in Hindu cosmology as Kashi - the City of Light - this sacred metropolis rises in a grand stone amphitheatre along the crescent curve of the River Ganges. Here, for nearly three millennia, life, death, and spiritual transcendence have played out in an unbroken public theatre along 84 colossal stone ghats.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$12°C - 26°C Day / 7°C - 14°C Night$$,
    $$5 to 7 Days$$,
    $$["Dawn Classical Raga Cruise aboard a Private Bajra Barge: Private wooden barge charter gliding past all 84 ghats at daybreak, accompanied by live morning ragas performe...","Reserved VIP Balcony Viewing of the Evening Ganga Maha Aarti: Exclusive front-row river mooring or private palace rooftop terrace vantage at Dashashwamedh Ghat, watching se...","Private Madanpura Silk Atelier & Master Weaver Masterclass: Behind-the-scenes access to a 7th-generation master weaver's private haveli, witnessing the intricate jacquard...","Scholar-Guided Archaeological Dawn Walking Tour of Sarnath: Private dawn exploration of the Dhamek Stupa, the ruins of ancient monasteries, and the Ashoka Lion Capital mu...","Private Vedic Astrological & Philosophical Consultation: Private intellectual discourse and personal Sanskrit birth-chart reading with a 5th-generation Vedic scholar a..."]$$::jsonb,
    $$["/images/destinations/varanasi/hero.jpg","/images/destinations/varanasi/sunrise-boat-ghats.jpg","/images/destinations/varanasi/evening-ganga-aarti.jpg","/images/destinations/varanasi/sarnath-dhamek-stupa.jpg","/images/destinations/varanasi/ramnagar-fort.jpg","/images/destinations/varanasi/hotel-taj-ganges.jpg"]$$::jsonb,
    true
  ),
(
    'ranthambore',
    'Ranthambore & Royal Wilds',
    'Central India',
    $$Private Bengal Tiger Safaris in Ancient Jungle Ruins$$,
    '/images/destinations/ranthambore/hero.jpg',
    $$Ranthambore is where the wild drama of the Indian jungle collides with the romantic decay of imperial history. Spanning over 1,300 square kilometers of dry deciduous forest, rocky escarpments, and open meadows in southeastern Rajasthan, this legendary landscape is governed by *Panthera tigris tigris* - the Royal Bengal tiger. Here, big cats do not merely prowl through dense bamboo thickets; they stroll through the stone courtyards of abandoned medieval mosques, rest beside ancient banyan-draped cenotaphs, and hunt sambar deer along the shores of lotus-carpeted lakes.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$15°C - 27°C Day / 7°C - 12°C Night$$,
    $$4 to 6 Days$$,
    $$["Private Open-Top 4x4 Safari across Core Zones 1 to 5: Exclusive morning and afternoon game drives in customized open 4x4 safari vehicles accompanied by a master tra...","Sunset Champagne Walk atop Ranthambore Fort: Private guided ascent through the monumental gateways of the 10th-century fortress with a heritage scholar, en...","Private River Safari on the National Chambal Sanctuary: Private chartered boat expedition along the protected waters of the Chambal River, guided by a herpetologist t...","Naturalist Storytelling & Photography Masterclass at SUJÁN Sher Bagh: Intimate fireside masterclass with an award-winning wildlife photographer and tracker, reviewing high-speed ca...","Dawn Birding & Wilderness Walk around Mansarovar & Surwal Lakes: Private dawn walking expedition with a specialist ornithologist around local freshwater lakes, spotting thousa..."]$$::jsonb,
    $$["/images/destinations/ranthambore/hero.jpg","/images/destinations/ranthambore/tiger-stalking-banyan.jpg","/images/destinations/ranthambore/ranthambore-hill-fort.jpg","/images/destinations/ranthambore/chambal-sanctuary.jpg","/images/destinations/ranthambore/hotel-sujan-sher-bagh.jpg","/images/destinations/ranthambore/hotel-oberoi-vanyavilas.jpg"]$$::jsonb,
    true
  ),
(
    'goa',
    'Goa & Portuguese Heritage Coast',
    'Western India',
    $$Colonial Mansions, Private Catamarans & Coastal Haute Cuisine$$,
    '/images/destinations/goa/hero.jpg',
    $$Goa is defined by a gentle, tropical rhythm born from four and a half centuries of Portuguese maritime dominion along the sun-drenched Konkan coast. Quite distinct from the rest of the Indian subcontinent, the spirit of Goa - captured in the local philosophy of *susegad* (a relaxed, contented state of mind) - is felt in the rustle of coconut palm fronds, the tolling of white church bells across emerald paddy fields, and the salty breeze blowing in from the Arabian Sea.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$22°C - 32°C Day / 18°C - 22°C Night$$,
    $$5 to 8 Days$$,
    $$["Private Sunset Charter aboard a Luxury Catamaran, Mandovi Estuary: Private yacht or catamaran charter navigating from the Mandovi River out into Aguada Bay, accompanied by chill...","Architectural Walking Salon in Fontainhas with a Conservation Scholar: Private guided walk through the Latin Quarter with a renowned Indo-Portuguese architectural preservationist, g...","Private After-Hours Exploration of the Basilica of Bom Jesus, Old Goa: Exclusive after-hours access to the sacred sanctuaries and sacristy of the UNESCO-listed Basilica of Bom Jesus...","Artisanal Feni Distillation Masterclass on a Heritage Cashew Plantation: Private excursion to a secluded family-owned estate in Valpoi or Ponda, observing traditional wood-fired coppe...","Private Dolphin & Secret Cove Yacht Cruise to the Grand Island Reefs: Morning yacht excursion around the headlands of Cabo de Rama and Grand Island, tracking Indo-Pacific humpback ..."]$$::jsonb,
    $$["/images/destinations/goa/hero.jpg","/images/destinations/goa/fontainhas-latin-quarter.jpg","/images/destinations/goa/heritage-portuguese-mansion.jpg","/images/destinations/goa/private-catamaran-sunset.jpg","/images/destinations/goa/secluded-cove-sunset.jpg","/images/destinations/goa/hotel-taj-exotica.jpg"]$$::jsonb,
    true
  ),
(
    'kashmir',
    'Kashmir & The Vale of Srinagar',
    'Himalayas & Ladakh',
    $$Mughal Garden Terraces, Cedar Houseboats & Alpine Splendor$$,
    '/images/destinations/kashmir/hero.jpg',
    $$Framed by the snow-crowned amphitheatre of the Pir Panjal and Great Himalayan ranges, the Vale of Kashmir has been celebrated for centuries as heaven on earth (*Firdaus bar roo-ye zameen*). At the heart of this high-altitude basin lies Srinagar, a city organized around the aquatic poetry of Dal and Nigeen Lakes. Here, morning mist rises from still waters like spun silk, revealing hundreds of intricately carved cedar-wood houseboats, their Victorian fretwork reflected in mirror-smooth water lilies.$$,
    $$March to May (Spring Blossom & Tulip Radiance - prime touring climate)$$,
    $$10°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Private Cedar Shikara to the Floating Dawn Market: Private morning navigation aboard a luxury cedar shikara across mist-covered Dal Lake to the 200-year-old floa...","Curator-Led Architectural Walk of Shalimar & Nishat Mughal Gardens: Private after-hours exploration of the Mughal pleasure gardens with an architectural historian, examining the ...","Hangul Deer Tracking Expedition in Dachigam National Park: Exclusive morning wildlife safari in Dachigam National Park with a senior wildlife biologist, tracking the cri...","Master Atelier Visit: Authentic Kani & Sozni Pashmina Guilds: Behind-the-scenes access to a multigenerational family karkhana (workshop) in the Old City of Srinagar, observ...","Helicopter Flight & Gondola Ascent to Apharwat Peak, Gulmarg: Private helicopter transfer to Gulmarg, followed by VIP skip-the-line boarding on the Gulmarg Gondola to Aphar..."]$$::jsonb,
    $$["/images/destinations/kashmir/hero.jpg","/images/destinations/kashmir/dal-lake-shikara.jpg","/images/destinations/kashmir/mughal-gardens.jpg","/images/destinations/kashmir/gulmarg-himalayas.jpg"]$$::jsonb,
    true
  ),
(
    'central-india',
    'Central India & Khajuraho Heritage Corridor',
    'Central India',
    $$Medieval Dynastic Temples, River Cenotaphs & Sovereign Tiger Forests$$,
    '/images/destinations/central-india/hero.jpg',
    $$The Central Indian heritage corridor encompasses a majestic cross-section of Indian antiquity. Stretching from the sandstone temple hills of Khajuraho across the medieval fortresses of Orchha to the dense sal forests of Bandhavgarh and Kanha, this is a realm where the boundary between human artistry and primeval nature dissolves entirely.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$10°C - 26°C Day / 4°C - 10°C Night$$,
    $$6 to 9 Days$$,
    $$["Private Sunrise Architectural Tour of the Western Group of Khajuraho: Private, early morning access to the Kandariya Mahadeva and Lakshmana temples with a senior archaeological sch...","Twilight Flute & Sitar Salon at the Orchha Cenotaphs on the River Betwa: Private candlelit reception on the banks of the Betwa River directly facing the illuminated Bundela cenotaphs,...","Private Core-Zone Tiger Tracking in Bandhavgarh with Master Naturalists: Full-day private safari permit across the Tala and Magdhi core zones in an open 4x4 safari vehicle, tracking t...","Dawn Barasingha Safari across Kanha's Maiden Grasslands: Morning game drive across the mist-covered central meadows of Kanha, observing the rare hard-ground barasingha...","Private River Safari on the Ken River Canyon, Panna: Boat expedition through the deep sandstone gorges of the Ken River inside Panna Tiger Reserve, observing nesti..."]$$::jsonb,
    $$["/images/destinations/central-india/hero.jpg","/images/destinations/central-india/orchha-palace.jpg","/images/destinations/central-india/orchha-cenotaphs.jpg","/images/destinations/central-india/bandhavgarh-tiger.jpg"]$$::jsonb,
    true
  ),
(
    'tamil-nadu',
    'Tamil Nadu & The Great Living Chola Temples',
    'South India',
    $$Imperial Granite Vimanas, Merchant Palaces & Sacred Classical Arts$$,
    '/images/destinations/tamil-nadu/hero.jpg',
    $$Tamil Nadu is the guardian of unbroken Dravidian civilization. Unlike northern realms whose architectural monuments were repeatedly reshaped by successive waves of conquest, the Cauvery Delta and southern plains of Tamil Nadu have preserved their classical language, ritual temple architecture, and philosophical traditions for more than two millennia. This is an empire of monumental granite, where soaring temple towers (*gopurams*) encrusted with thousands of painted deities dominate the palm-fringed horizon.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$20°C - 30°C$$,
    $$7 to 10 Days$$,
    $$["Private Pre-Dawn VIP Darshan at Brihadisvara Temple, Thanjavur: Curator-led private dawn access to the inner corridors and courtyards of the Great Chola Temple before public ...","Private Twilight Temple Procession at Madurai Meenakshi Temple: Exclusive VIP entry to witness the sacred night procession (*palliyarai*) at the Meenakshi Amman Temple, as th...","Architectural Exploration of Private Chettinad Mansions: Private walking tour of Kanadukathan and Kottaiyur led by a Chettinad heritage conservationist, gaining exclus...","Master Lost-Wax Bronze Casting Masterclass in Swamimalai: Private workshop visit to a 10th-generation master sthapathi family in Swamimalai, observing the creation of b...","Private Chamber Carnatic Veena or Vocal Recital: Intimate evening chamber concert inside the central courtyard of Visalam or Svatma, featuring renowned classic..."]$$::jsonb,
    $$["/images/destinations/tamil-nadu/hero.jpg","/images/destinations/tamil-nadu/thanjavur-temple.jpg","/images/destinations/tamil-nadu/madurai-meenakshi.jpg","/images/destinations/tamil-nadu/chettinad-mansion.jpg","/images/destinations/tamil-nadu/mahabalipuram-shore-temple.jpg","/images/destinations/tamil-nadu/hotel-the-leela-chennai.jpg"]$$::jsonb,
    true
  ),
(
    'hampi',
    'Hampi & The Vijayanagara Imperial Ruins',
    'South India',
    $$Monolithic Granite Ruins, Mythic Boulders & Forgotten Empires$$,
    '/images/destinations/hampi/hero.jpg',
    $$Hampi exists in an otherworldly realm where human architectural ambition meets primeval geological fantasy. Spread across 4,000 hectares of rugged terrain in north-central Karnataka, the landscape is defined by millions of giant, rust-colored granite boulders precariously balanced across arid hillsides, bisected by the emerald currents of the sacred Tungabhadra River.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$16°C - 30°C$$,
    $$4 to 6 Days$$,
    $$["Private Coracle River Glide along the Tungabhadra at Dawn: Private sunrise excursion in a traditional wicker coracle boat across the quiet currents of the Tungabhadra, f...","Curator-Led Architectural Exploration of the Vittala Temple: Exclusive pre-opening access to the Vittala Temple complex with an epigraphist and architectural historian, ex...","Private Sunset Champagne Reception atop Malyavanta Hill: Private evening ascent to Malyavanta Raghunatha Temple or Hemakuta Hill, sipping chilled champagne on the warm...","Curated Expedition to the 6th-Century Rock Caves of Badami & Pattadakal: Private full-day excursion in a luxury SUV to the red sandstone cave temples of Badami and the UNESCO temples ...","Private Corbelled Bathing & Royal Court Dinner at Evolve Back: Multi-course imperial court dinner hosted on the private terrace of Kamalapura Palace, featuring royal Vijayan..."]$$::jsonb,
    $$["/images/destinations/hampi/hero.jpg","/images/destinations/hampi/virupaksha-temple.jpg","/images/destinations/hampi/tungabhadra-river.jpg","/images/destinations/hampi/hotel-evolve-back.jpg"]$$::jsonb,
    true
  ),
(
    'gujarat',
    'The White Desert & Royal Kingdoms of Gujarat',
    'Western India',
    $$White Salt Expanses, Asiatic Lions & Imperial Solanki Heritage$$,
    '/images/destinations/gujarat/hero.jpg',
    $$Gujarat is a land of luminous contrasts, where boundless desert wilderness meets centuries of mercantile wealth and imperial craftsmanship. Along the northern frontier lies the Great Rann of Kutch - the world's largest seasonal salt desert. Stretching toward the horizon in a blinding expanse of pure white salt crystals, this surreal landscape reflects the sky like a giant mirror. Under the light of a full moon, the Rann turns into a dreamscape of shimmering silver, home to semi-nomadic artisan communities whose vibrant hand-embroideries bring brilliant color to the barren earth.$$,
    $$October to March (Golden Winter / Salt Desert Season - prime touring climate)$$,
    $$12°C - 28°C Day / 8°C - 14°C Night$$,
    $$7 to 10 Days$$,
    $$["Full-Moon Midnight Excursion on the Great Rann of Kutch: Private evening expedition into the silent, white salt flats under the radiance of the full moon, accompanied ...","Private Open-Top 4x4 Asiatic Lion Safari in Gir National Park: Exclusive morning and evening game drives in Gir's core wildlife tracking zone led by a senior naturalist and ...","Masterclass with the Master of Rogan Art in Nirona: Private studio session in Nirona village with the Khatri family, observing the transformation of boiled castor...","Curator Salon at the Patan Patola Double-Ikat Silk Loom: Exclusive visit to the private home-museum of the Salvi master weavers in Patan, witnessing the mathematical d...","Private Dawn Exploration of Rani ki Vav & Modhera Sun Temple: Curator-led private dawn visit to the UNESCO stepwell of Rani ki Vav and the Modhera Sun Temple before public ..."]$$::jsonb,
    $$["/images/destinations/gujarat/hero.jpg","/images/destinations/gujarat/modhera-sun-temple.jpg","/images/destinations/gujarat/gir-asiatic-lion.jpg","/images/destinations/gujarat/rani-ki-vav.jpg","/images/destinations/gujarat/hotel-aramness-gir.jpg","/images/destinations/gujarat/hotel-rann-luxury-camp.jpg"]$$::jsonb,
    true
  ),
(
    'sikkim-darjeeling',
    'Sikkim & Darjeeling Eastern Himalayas',
    'Himalayas & Ladakh',
    $$Planter Tea Terroirs, Sacred Kanchenjunga & Ancient Nyingma Gompas$$,
    '/images/destinations/sikkim-darjeeling/hero.jpg',
    $$The Eastern Himalayas of Darjeeling and Sikkim rise in steep, mist-shrouded green terraces toward the third highest mountain on earth: Mount Kanchenjunga (8,586 m). Here, where Tibetan Buddhism meets British colonial hill-station heritage, the air is scented with woodsmoke, mountain pine, and the fragrant, floral aroma of freshly plucked tea leaves.$$,
    $$March to May (Himalayan Spring / Orchid & Blossom Season - prime touring climate)$$,
    $$12°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Kanchenjunga Viewing & Planter's High Tea at Glenburn: Private sunrise tea service on the Simbong terrace of Glenburn Tea Estate, watching the dawn sunlight turn the...","Master Tea Taster Workshop & Plucking Masterclass, Glenburn: Private walking masterclass through the tea gardens with the estate manager, learning the delicate art of harv...","Private Steam Train Charter on the UNESCO Darjeeling Himalayan Railway: Private chartered steam locomotive ride aboard the historic 1881 \"Toy Train\" from Darjeeling to Ghoom, passing...","Private Monastic Puja & Blessing at Pemayangtse Monastery: Private dawn prayer ceremony inside the 18th-century prayer hall of Pemayangtse Gompa, receiving a silk ceremo...","Curator Tour of the Golden Stupa & Sacred Art Relics at Rumtek: Private guided exploration of Rumtek Monastery and its sacred art collection with a resident scholar of Buddhi..."]$$::jsonb,
    $$["/images/destinations/sikkim-darjeeling/hero.jpg","/images/destinations/sikkim-darjeeling/glenburn-tea-estate.jpg","/images/destinations/sikkim-darjeeling/rumtek-monastery.jpg","/images/destinations/sikkim-darjeeling/tea-ritual.jpg"]$$::jsonb,
    true
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  tagline = EXCLUDED.tagline,
  hero_image = EXCLUDED.hero_image,
  description = EXCLUDED.description,
  best_time_to_visit = EXCLUDED.best_time_to_visit,
  weather_info = EXCLUDED.weather_info,
  ideal_duration = EXCLUDED.ideal_duration,
  highlights = EXCLUDED.highlights,
  gallery = EXCLUDED.gallery,
  is_featured = EXCLUDED.is_featured; they stroll through the stone courtyards of abandoned medieval mosques, rest beside ancient banyan-draped cenotaphs, and hunt sambar deer along the shores of lotus-carpeted lakes.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$15°C - 27°C Day / 7°C - 12°C Night$$,
    $$4 to 6 Days$$,
    $$["Private Open-Top 4x4 Safari across Core Zones 1 to 5: Exclusive morning and afternoon game drives in customized open 4x4 safari vehicles accompanied by a master tra...","Sunset Champagne Walk atop Ranthambore Fort: Private guided ascent through the monumental gateways of the 10th-century fortress with a heritage scholar, en...","Private River Safari on the National Chambal Sanctuary: Private chartered boat expedition along the protected waters of the Chambal River, guided by a herpetologist t...","Naturalist Storytelling & Photography Masterclass at SUJÁN Sher Bagh: Intimate fireside masterclass with an award-winning wildlife photographer and tracker, reviewing high-speed ca...","Dawn Birding & Wilderness Walk around Mansarovar & Surwal Lakes: Private dawn walking expedition with a specialist ornithologist around local freshwater lakes, spotting thousa..."]$$::jsonb,
    $$["/images/destinations/ranthambore/hero.jpg","/images/destinations/ranthambore/tiger-stalking-banyan.jpg","/images/destinations/ranthambore/ranthambore-hill-fort.jpg","/images/destinations/ranthambore/chambal-sanctuary.jpg","/images/destinations/ranthambore/hotel-sujan-sher-bagh.jpg","/images/destinations/ranthambore/hotel-oberoi-vanyavilas.jpg"]$$::jsonb,
    true
  ),
(
    'goa',
    'Goa & Portuguese Heritage Coast',
    'Western India',
    $$Colonial Mansions, Private Catamarans & Coastal Haute Cuisine$$,
    '/images/destinations/goa/hero.jpg',
    $$Goa is defined by a gentle, tropical rhythm born from four and a half centuries of Portuguese maritime dominion along the sun-drenched Konkan coast. Quite distinct from the rest of the Indian subcontinent, the spirit of Goa - captured in the local philosophy of *susegad* (a relaxed, contented state of mind) - is felt in the rustle of coconut palm fronds, the tolling of white church bells across emerald paddy fields, and the salty breeze blowing in from the Arabian Sea.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$22°C - 32°C Day / 18°C - 22°C Night$$,
    $$5 to 8 Days$$,
    $$["Private Sunset Charter aboard a Luxury Catamaran, Mandovi Estuary: Private yacht or catamaran charter navigating from the Mandovi River out into Aguada Bay, accompanied by chill...","Architectural Walking Salon in Fontainhas with a Conservation Scholar: Private guided walk through the Latin Quarter with a renowned Indo-Portuguese architectural preservationist, g...","Private After-Hours Exploration of the Basilica of Bom Jesus, Old Goa: Exclusive after-hours access to the sacred sanctuaries and sacristy of the UNESCO-listed Basilica of Bom Jesus...","Artisanal Feni Distillation Masterclass on a Heritage Cashew Plantation: Private excursion to a secluded family-owned estate in Valpoi or Ponda, observing traditional wood-fired coppe...","Private Dolphin & Secret Cove Yacht Cruise to the Grand Island Reefs: Morning yacht excursion around the headlands of Cabo de Rama and Grand Island, tracking Indo-Pacific humpback ..."]$$::jsonb,
    $$["/images/destinations/goa/hero.jpg","/images/destinations/goa/fontainhas-latin-quarter.jpg","/images/destinations/goa/heritage-portuguese-mansion.jpg","/images/destinations/goa/private-catamaran-sunset.jpg","/images/destinations/goa/secluded-cove-sunset.jpg","/images/destinations/goa/hotel-taj-exotica.jpg"]$$::jsonb,
    true
  ),
(
    'kashmir',
    'Kashmir & The Vale of Srinagar',
    'Himalayas & Ladakh',
    $$Mughal Garden Terraces, Cedar Houseboats & Alpine Splendor$$,
    '/images/destinations/kashmir/hero.jpg',
    $$Framed by the snow-crowned amphitheatre of the Pir Panjal and Great Himalayan ranges, the Vale of Kashmir has been celebrated for centuries as heaven on earth (*Firdaus bar roo-ye zameen*). At the heart of this high-altitude basin lies Srinagar, a city organized around the aquatic poetry of Dal and Nigeen Lakes. Here, morning mist rises from still waters like spun silk, revealing hundreds of intricately carved cedar-wood houseboats, their Victorian fretwork reflected in mirror-smooth water lilies.$$,
    $$March to May (Spring Blossom & Tulip Radiance - prime touring climate)$$,
    $$10°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Private Cedar Shikara to the Floating Dawn Market: Private morning navigation aboard a luxury cedar shikara across mist-covered Dal Lake to the 200-year-old floa...","Curator-Led Architectural Walk of Shalimar & Nishat Mughal Gardens: Private after-hours exploration of the Mughal pleasure gardens with an architectural historian, examining the ...","Hangul Deer Tracking Expedition in Dachigam National Park: Exclusive morning wildlife safari in Dachigam National Park with a senior wildlife biologist, tracking the cri...","Master Atelier Visit: Authentic Kani & Sozni Pashmina Guilds: Behind-the-scenes access to a multigenerational family karkhana (workshop) in the Old City of Srinagar, observ...","Helicopter Flight & Gondola Ascent to Apharwat Peak, Gulmarg: Private helicopter transfer to Gulmarg, followed by VIP skip-the-line boarding on the Gulmarg Gondola to Aphar..."]$$::jsonb,
    $$["/images/destinations/kashmir/hero.jpg","/images/destinations/kashmir/dal-lake-shikara.jpg","/images/destinations/kashmir/mughal-gardens.jpg","/images/destinations/kashmir/gulmarg-himalayas.jpg"]$$::jsonb,
    true
  ),
(
    'central-india',
    'Central India & Khajuraho Heritage Corridor',
    'Central India',
    $$Medieval Dynastic Temples, River Cenotaphs & Sovereign Tiger Forests$$,
    '/images/destinations/central-india/hero.jpg',
    $$The Central Indian heritage corridor encompasses a majestic cross-section of Indian antiquity. Stretching from the sandstone temple hills of Khajuraho across the medieval fortresses of Orchha to the dense sal forests of Bandhavgarh and Kanha, this is a realm where the boundary between human artistry and primeval nature dissolves entirely.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$10°C - 26°C Day / 4°C - 10°C Night$$,
    $$6 to 9 Days$$,
    $$["Private Sunrise Architectural Tour of the Western Group of Khajuraho: Private, early morning access to the Kandariya Mahadeva and Lakshmana temples with a senior archaeological sch...","Twilight Flute & Sitar Salon at the Orchha Cenotaphs on the River Betwa: Private candlelit reception on the banks of the Betwa River directly facing the illuminated Bundela cenotaphs,...","Private Core-Zone Tiger Tracking in Bandhavgarh with Master Naturalists: Full-day private safari permit across the Tala and Magdhi core zones in an open 4x4 safari vehicle, tracking t...","Dawn Barasingha Safari across Kanha's Maiden Grasslands: Morning game drive across the mist-covered central meadows of Kanha, observing the rare hard-ground barasingha...","Private River Safari on the Ken River Canyon, Panna: Boat expedition through the deep sandstone gorges of the Ken River inside Panna Tiger Reserve, observing nesti..."]$$::jsonb,
    $$["/images/destinations/central-india/hero.jpg","/images/destinations/central-india/khajuraho-temple.jpg","/images/destinations/central-india/orchha-cenotaphs.jpg","/images/destinations/central-india/bandhavgarh-tiger.jpg"]$$::jsonb,
    true
  ),
(
    'tamil-nadu',
    'Tamil Nadu & The Great Living Chola Temples',
    'South India',
    $$Imperial Granite Vimanas, Merchant Palaces & Sacred Classical Arts$$,
    '/images/destinations/tamil-nadu/hero.jpg',
    $$Tamil Nadu is the guardian of unbroken Dravidian civilization. Unlike northern realms whose architectural monuments were repeatedly reshaped by successive waves of conquest, the Cauvery Delta and southern plains of Tamil Nadu have preserved their classical language, ritual temple architecture, and philosophical traditions for more than two millennia. This is an empire of monumental granite, where soaring temple towers (*gopurams*) encrusted with thousands of painted deities dominate the palm-fringed horizon.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$20°C - 30°C$$,
    $$7 to 10 Days$$,
    $$["Private Pre-Dawn VIP Darshan at Brihadisvara Temple, Thanjavur: Curator-led private dawn access to the inner corridors and courtyards of the Great Chola Temple before public ...","Private Twilight Temple Procession at Madurai Meenakshi Temple: Exclusive VIP entry to witness the sacred night procession (*palliyarai*) at the Meenakshi Amman Temple, as th...","Architectural Exploration of Private Chettinad Mansions: Private walking tour of Kanadukathan and Kottaiyur led by a Chettinad heritage conservationist, gaining exclus...","Master Lost-Wax Bronze Casting Masterclass in Swamimalai: Private workshop visit to a 10th-generation master sthapathi family in Swamimalai, observing the creation of b...","Private Chamber Carnatic Veena or Vocal Recital: Intimate evening chamber concert inside the central courtyard of Visalam or Svatma, featuring renowned classic..."]$$::jsonb,
    $$["/images/destinations/tamil-nadu/hero.jpg","/images/destinations/tamil-nadu/thanjavur-temple.jpg","/images/destinations/tamil-nadu/madurai-meenakshi.jpg","/images/destinations/tamil-nadu/chettinad-mansion.jpg","/images/destinations/tamil-nadu/mahabalipuram-shore-temple.jpg","/images/destinations/tamil-nadu/hotel-the-leela-chennai.jpg"]$$::jsonb,
    true
  ),
(
    'hampi',
    'Hampi & The Vijayanagara Imperial Ruins',
    'South India',
    $$Monolithic Granite Ruins, Mythic Boulders & Forgotten Empires$$,
    '/images/destinations/hampi/hero.jpg',
    $$Hampi exists in an otherworldly realm where human architectural ambition meets primeval geological fantasy. Spread across 4,000 hectares of rugged terrain in north-central Karnataka, the landscape is defined by millions of giant, rust-colored granite boulders precariously balanced across arid hillsides, bisected by the emerald currents of the sacred Tungabhadra River.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$16°C - 30°C$$,
    $$4 to 6 Days$$,
    $$["Private Coracle River Glide along the Tungabhadra at Dawn: Private sunrise excursion in a traditional wicker coracle boat across the quiet currents of the Tungabhadra, f...","Curator-Led Architectural Exploration of the Vittala Temple: Exclusive pre-opening access to the Vittala Temple complex with an epigraphist and architectural historian, ex...","Private Sunset Champagne Reception atop Malyavanta Hill: Private evening ascent to Malyavanta Raghunatha Temple or Hemakuta Hill, sipping chilled champagne on the warm...","Curated Expedition to the 6th-Century Rock Caves of Badami & Pattadakal: Private full-day excursion in a luxury SUV to the red sandstone cave temples of Badami and the UNESCO temples ...","Private Corbelled Bathing & Royal Court Dinner at Evolve Back: Multi-course imperial court dinner hosted on the private terrace of Kamalapura Palace, featuring royal Vijayan..."]$$::jsonb,
    $$["/images/destinations/hampi/hero.jpg","/images/destinations/hampi/virupaksha-temple.jpg","/images/destinations/hampi/tungabhadra-river.jpg","/images/destinations/hampi/hotel-evolve-back.jpg"]$$::jsonb,
    true
  ),
(
    'gujarat',
    'The White Desert & Royal Kingdoms of Gujarat',
    'Western India',
    $$White Salt Expanses, Asiatic Lions & Imperial Solanki Heritage$$,
    '/images/destinations/gujarat/hero.jpg',
    $$Gujarat is a land of luminous contrasts, where boundless desert wilderness meets centuries of mercantile wealth and imperial craftsmanship. Along the northern frontier lies the Great Rann of Kutch - the world's largest seasonal salt desert. Stretching toward the horizon in a blinding expanse of pure white salt crystals, this surreal landscape reflects the sky like a giant mirror. Under the light of a full moon, the Rann turns into a dreamscape of shimmering silver, home to semi-nomadic artisan communities whose vibrant hand-embroideries bring brilliant color to the barren earth.$$,
    $$October to March (Golden Winter / Salt Desert Season - prime touring climate)$$,
    $$12°C - 28°C Day / 8°C - 14°C Night$$,
    $$7 to 10 Days$$,
    $$["Full-Moon Midnight Excursion on the Great Rann of Kutch: Private evening expedition into the silent, white salt flats under the radiance of the full moon, accompanied ...","Private Open-Top 4x4 Asiatic Lion Safari in Gir National Park: Exclusive morning and evening game drives in Gir's core wildlife tracking zone led by a senior naturalist and ...","Masterclass with the Master of Rogan Art in Nirona: Private studio session in Nirona village with the Khatri family, observing the transformation of boiled castor...","Curator Salon at the Patan Patola Double-Ikat Silk Loom: Exclusive visit to the private home-museum of the Salvi master weavers in Patan, witnessing the mathematical d...","Private Dawn Exploration of Rani ki Vav & Modhera Sun Temple: Curator-led private dawn visit to the UNESCO stepwell of Rani ki Vav and the Modhera Sun Temple before public ..."]$$::jsonb,
    $$["/images/destinations/gujarat/hero.jpg","/images/destinations/gujarat/modhera-sun-temple.jpg","/images/destinations/gujarat/gir-asiatic-lion.jpg","/images/destinations/gujarat/rani-ki-vav.jpg","/images/destinations/gujarat/hotel-aramness-gir.jpg","/images/destinations/gujarat/hotel-rann-luxury-camp.jpg"]$$::jsonb,
    true
  ),
(
    'sikkim-darjeeling',
    'Sikkim & Darjeeling Eastern Himalayas',
    'Himalayas & Ladakh',
    $$Planter Tea Terroirs, Sacred Kanchenjunga & Ancient Nyingma Gompas$$,
    '/images/destinations/sikkim-darjeeling/hero.jpg',
    $$The Eastern Himalayas of Darjeeling and Sikkim rise in steep, mist-shrouded green terraces toward the third highest mountain on earth: Mount Kanchenjunga (8,586 m). Here, where Tibetan Buddhism meets British colonial hill-station heritage, the air is scented with woodsmoke, mountain pine, and the fragrant, floral aroma of freshly plucked tea leaves.$$,
    $$March to May (Himalayan Spring / Orchid & Blossom Season - prime touring climate)$$,
    $$12°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Kanchenjunga Viewing & Planter's High Tea at Glenburn: Private sunrise tea service on the Simbong terrace of Glenburn Tea Estate, watching the dawn sunlight turn the...","Master Tea Taster Workshop & Plucking Masterclass, Glenburn: Private walking masterclass through the tea gardens with the estate manager, learning the delicate art of harv...","Private Steam Train Charter on the UNESCO Darjeeling Himalayan Railway: Private chartered steam locomotive ride aboard the historic 1881 \"Toy Train\" from Darjeeling to Ghoom, passing...","Private Monastic Puja & Blessing at Pemayangtse Monastery: Private dawn prayer ceremony inside the 18th-century prayer hall of Pemayangtse Gompa, receiving a silk ceremo...","Curator Tour of the Golden Stupa & Sacred Art Relics at Rumtek: Private guided exploration of Rumtek Monastery and its sacred art collection with a resident scholar of Buddhi..."]$$::jsonb,
    $$["/images/destinations/sikkim-darjeeling/hero.jpg","/images/destinations/sikkim-darjeeling/glenburn-tea-estate.jpg","/images/destinations/sikkim-darjeeling/rumtek-monastery.jpg","/images/destinations/sikkim-darjeeling/tea-ritual.jpg"]$$::jsonb,
    true
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  tagline = EXCLUDED.tagline,
  hero_image = EXCLUDED.hero_image,
  description = EXCLUDED.description,
  best_time_to_visit = EXCLUDED.best_time_to_visit,
  weather_info = EXCLUDED.weather_info,
  ideal_duration = EXCLUDED.ideal_duration,
  highlights = EXCLUDED.highlights,
  gallery = EXCLUDED.gallery,
  is_featured = EXCLUDED.is_featured; they stroll through the stone courtyards of abandoned medieval mosques, rest beside ancient banyan-draped cenotaphs, and hunt sambar deer along the shores of lotus-carpeted lakes.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$15°C - 27°C Day / 7°C - 12°C Night$$,
    $$4 to 6 Days$$,
    $$["Private Open-Top 4x4 Safari across Core Zones 1 to 5: Exclusive morning and afternoon game drives in customized open 4x4 safari vehicles accompanied by a master tra...","Sunset Champagne Walk atop Ranthambore Fort: Private guided ascent through the monumental gateways of the 10th-century fortress with a heritage scholar, en...","Private River Safari on the National Chambal Sanctuary: Private chartered boat expedition along the protected waters of the Chambal River, guided by a herpetologist t...","Naturalist Storytelling & Photography Masterclass at SUJÁN Sher Bagh: Intimate fireside masterclass with an award-winning wildlife photographer and tracker, reviewing high-speed ca...","Dawn Birding & Wilderness Walk around Mansarovar & Surwal Lakes: Private dawn walking expedition with a specialist ornithologist around local freshwater lakes, spotting thousa..."]$$::jsonb,
    $$["/images/destinations/ranthambore/hero.jpg","/images/destinations/ranthambore/tiger-stalking-banyan.jpg","/images/destinations/ranthambore/ranthambore-hill-fort.jpg","/images/destinations/ranthambore/chambal-sanctuary.jpg","/images/destinations/ranthambore/hotel-sujan-sher-bagh.jpg","/images/destinations/ranthambore/hotel-oberoi-vanyavilas.jpg"]$$::jsonb,
    true
  ),
(
    'goa',
    'Goa & Portuguese Heritage Coast',
    'Western India',
    $$Colonial Mansions, Private Catamarans & Coastal Haute Cuisine$$,
    '/images/destinations/goa/hero.jpg',
    $$Goa is defined by a gentle, tropical rhythm born from four and a half centuries of Portuguese maritime dominion along the sun-drenched Konkan coast. Quite distinct from the rest of the Indian subcontinent, the spirit of Goa - captured in the local philosophy of *susegad* (a relaxed, contented state of mind) - is felt in the rustle of coconut palm fronds, the tolling of white church bells across emerald paddy fields, and the salty breeze blowing in from the Arabian Sea.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$22°C - 32°C Day / 18°C - 22°C Night$$,
    $$5 to 8 Days$$,
    $$["Private Sunset Charter aboard a Luxury Catamaran, Mandovi Estuary: Private yacht or catamaran charter navigating from the Mandovi River out into Aguada Bay, accompanied by chill...","Architectural Walking Salon in Fontainhas with a Conservation Scholar: Private guided walk through the Latin Quarter with a renowned Indo-Portuguese architectural preservationist, g...","Private After-Hours Exploration of the Basilica of Bom Jesus, Old Goa: Exclusive after-hours access to the sacred sanctuaries and sacristy of the UNESCO-listed Basilica of Bom Jesus...","Artisanal Feni Distillation Masterclass on a Heritage Cashew Plantation: Private excursion to a secluded family-owned estate in Valpoi or Ponda, observing traditional wood-fired coppe...","Private Dolphin & Secret Cove Yacht Cruise to the Grand Island Reefs: Morning yacht excursion around the headlands of Cabo de Rama and Grand Island, tracking Indo-Pacific humpback ..."]$$::jsonb,
    $$["/images/destinations/goa/hero.jpg","/images/destinations/goa/fontainhas-latin-quarter.jpg","/images/destinations/goa/heritage-portuguese-mansion.jpg","/images/destinations/goa/private-catamaran-sunset.jpg","/images/destinations/goa/secluded-cove-sunset.jpg","/images/destinations/goa/hotel-taj-exotica.jpg"]$$::jsonb,
    true
  ),
(
    'kashmir',
    'Kashmir & The Vale of Srinagar',
    'Himalayas & Ladakh',
    $$Mughal Garden Terraces, Cedar Houseboats & Alpine Splendor$$,
    '/images/destinations/kashmir/hero.jpg',
    $$Framed by the snow-crowned amphitheatre of the Pir Panjal and Great Himalayan ranges, the Vale of Kashmir has been celebrated for centuries as heaven on earth (*Firdaus bar roo-ye zameen*). At the heart of this high-altitude basin lies Srinagar, a city organized around the aquatic poetry of Dal and Nigeen Lakes. Here, morning mist rises from still waters like spun silk, revealing hundreds of intricately carved cedar-wood houseboats, their Victorian fretwork reflected in mirror-smooth water lilies.$$,
    $$March to May (Spring Blossom & Tulip Radiance - prime touring climate)$$,
    $$10°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Private Cedar Shikara to the Floating Dawn Market: Private morning navigation aboard a luxury cedar shikara across mist-covered Dal Lake to the 200-year-old floa...","Curator-Led Architectural Walk of Shalimar & Nishat Mughal Gardens: Private after-hours exploration of the Mughal pleasure gardens with an architectural historian, examining the ...","Hangul Deer Tracking Expedition in Dachigam National Park: Exclusive morning wildlife safari in Dachigam National Park with a senior wildlife biologist, tracking the cri...","Master Atelier Visit: Authentic Kani & Sozni Pashmina Guilds: Behind-the-scenes access to a multigenerational family karkhana (workshop) in the Old City of Srinagar, observ...","Helicopter Flight & Gondola Ascent to Apharwat Peak, Gulmarg: Private helicopter transfer to Gulmarg, followed by VIP skip-the-line boarding on the Gulmarg Gondola to Aphar..."]$$::jsonb,
    $$["/images/destinations/kashmir/hero.jpg","/images/destinations/kashmir/dal-lake-shikara.jpg","/images/destinations/kashmir/mughal-gardens.jpg","/images/destinations/kashmir/gulmarg-himalayas.jpg","/images/destinations/kashmir/kashmir-shikara-floating.jpg"]$$::jsonb,
    true
  ),
(
    'central-india',
    'Central India & Khajuraho Heritage Corridor',
    'Central India',
    $$Medieval Dynastic Temples, River Cenotaphs & Sovereign Tiger Forests$$,
    '/images/destinations/central-india/hero.jpg',
    $$The Central Indian heritage corridor encompasses a majestic cross-section of Indian antiquity. Stretching from the sandstone temple hills of Khajuraho across the medieval fortresses of Orchha to the dense sal forests of Bandhavgarh and Kanha, this is a realm where the boundary between human artistry and primeval nature dissolves entirely.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$10°C - 26°C Day / 4°C - 10°C Night$$,
    $$6 to 9 Days$$,
    $$["Private Sunrise Architectural Tour of the Western Group of Khajuraho: Private, early morning access to the Kandariya Mahadeva and Lakshmana temples with a senior archaeological sch...","Twilight Flute & Sitar Salon at the Orchha Cenotaphs on the River Betwa: Private candlelit reception on the banks of the Betwa River directly facing the illuminated Bundela cenotaphs,...","Private Core-Zone Tiger Tracking in Bandhavgarh with Master Naturalists: Full-day private safari permit across the Tala and Magdhi core zones in an open 4x4 safari vehicle, tracking t...","Dawn Barasingha Safari across Kanha's Maiden Grasslands: Morning game drive across the mist-covered central meadows of Kanha, observing the rare hard-ground barasingha...","Private River Safari on the Ken River Canyon, Panna: Boat expedition through the deep sandstone gorges of the Ken River inside Panna Tiger Reserve, observing nesti..."]$$::jsonb,
    $$["/images/destinations/central-india/hero.jpg","/images/destinations/central-india/khajuraho-temple.jpg","/images/destinations/central-india/orchha-cenotaphs.jpg","/images/destinations/central-india/bandhavgarh-tiger.jpg"]$$::jsonb,
    true
  ),
(
    'tamil-nadu',
    'Tamil Nadu & The Great Living Chola Temples',
    'South India',
    $$Imperial Granite Vimanas, Merchant Palaces & Sacred Classical Arts$$,
    '/images/destinations/tamil-nadu/hero.jpg',
    $$Tamil Nadu is the guardian of unbroken Dravidian civilization. Unlike northern realms whose architectural monuments were repeatedly reshaped by successive waves of conquest, the Cauvery Delta and southern plains of Tamil Nadu have preserved their classical language, ritual temple architecture, and philosophical traditions for more than two millennia. This is an empire of monumental granite, where soaring temple towers (*gopurams*) encrusted with thousands of painted deities dominate the palm-fringed horizon.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$20°C - 30°C$$,
    $$7 to 10 Days$$,
    $$["Private Pre-Dawn VIP Darshan at Brihadisvara Temple, Thanjavur: Curator-led private dawn access to the inner corridors and courtyards of the Great Chola Temple before public ...","Private Twilight Temple Procession at Madurai Meenakshi Temple: Exclusive VIP entry to witness the sacred night procession (*palliyarai*) at the Meenakshi Amman Temple, as th...","Architectural Exploration of Private Chettinad Mansions: Private walking tour of Kanadukathan and Kottaiyur led by a Chettinad heritage conservationist, gaining exclus...","Master Lost-Wax Bronze Casting Masterclass in Swamimalai: Private workshop visit to a 10th-generation master sthapathi family in Swamimalai, observing the creation of b...","Private Chamber Carnatic Veena or Vocal Recital: Intimate evening chamber concert inside the central courtyard of Visalam or Svatma, featuring renowned classic..."]$$::jsonb,
    $$["/images/destinations/tamil-nadu/hero.jpg","/images/destinations/tamil-nadu/thanjavur-temple.jpg","/images/destinations/tamil-nadu/madurai-meenakshi.jpg","/images/destinations/tamil-nadu/chettinad-mansion.jpg","/images/destinations/tamil-nadu/mahabalipuram-shore-temple.jpg","/images/destinations/tamil-nadu/hotel-the-leela-chennai.jpg"]$$::jsonb,
    true
  ),
(
    'hampi',
    'Hampi & The Vijayanagara Imperial Ruins',
    'South India',
    $$Monolithic Granite Ruins, Mythic Boulders & Forgotten Empires$$,
    '/images/destinations/hampi/hero.jpg',
    $$Hampi exists in an otherworldly realm where human architectural ambition meets primeval geological fantasy. Spread across 4,000 hectares of rugged terrain in north-central Karnataka, the landscape is defined by millions of giant, rust-colored granite boulders precariously balanced across arid hillsides, bisected by the emerald currents of the sacred Tungabhadra River.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$16°C - 30°C$$,
    $$4 to 6 Days$$,
    $$["Private Coracle River Glide along the Tungabhadra at Dawn: Private sunrise excursion in a traditional wicker coracle boat across the quiet currents of the Tungabhadra, f...","Curator-Led Architectural Exploration of the Vittala Temple: Exclusive pre-opening access to the Vittala Temple complex with an epigraphist and architectural historian, ex...","Private Sunset Champagne Reception atop Malyavanta Hill: Private evening ascent to Malyavanta Raghunatha Temple or Hemakuta Hill, sipping chilled champagne on the warm...","Curated Expedition to the 6th-Century Rock Caves of Badami & Pattadakal: Private full-day excursion in a luxury SUV to the red sandstone cave temples of Badami and the UNESCO temples ...","Private Corbelled Bathing & Royal Court Dinner at Evolve Back: Multi-course imperial court dinner hosted on the private terrace of Kamalapura Palace, featuring royal Vijayan..."]$$::jsonb,
    $$["/images/destinations/hampi/hero.jpg","/images/destinations/hampi/virupaksha-temple.jpg","/images/destinations/hampi/tungabhadra-river.jpg","/images/destinations/hampi/hotel-evolve-back.jpg"]$$::jsonb,
    true
  ),
(
    'gujarat',
    'The White Desert & Royal Kingdoms of Gujarat',
    'Western India',
    $$White Salt Expanses, Asiatic Lions & Imperial Solanki Heritage$$,
    '/images/destinations/gujarat/hero.jpg',
    $$Gujarat is a land of luminous contrasts, where boundless desert wilderness meets centuries of mercantile wealth and imperial craftsmanship. Along the northern frontier lies the Great Rann of Kutch - the world's largest seasonal salt desert. Stretching toward the horizon in a blinding expanse of pure white salt crystals, this surreal landscape reflects the sky like a giant mirror. Under the light of a full moon, the Rann turns into a dreamscape of shimmering silver, home to semi-nomadic artisan communities whose vibrant hand-embroideries bring brilliant color to the barren earth.$$,
    $$October to March (Golden Winter / Salt Desert Season - prime touring climate)$$,
    $$12°C - 28°C Day / 8°C - 14°C Night$$,
    $$7 to 10 Days$$,
    $$["Full-Moon Midnight Excursion on the Great Rann of Kutch: Private evening expedition into the silent, white salt flats under the radiance of the full moon, accompanied ...","Private Open-Top 4x4 Asiatic Lion Safari in Gir National Park: Exclusive morning and evening game drives in Gir's core wildlife tracking zone led by a senior naturalist and ...","Masterclass with the Master of Rogan Art in Nirona: Private studio session in Nirona village with the Khatri family, observing the transformation of boiled castor...","Curator Salon at the Patan Patola Double-Ikat Silk Loom: Exclusive visit to the private home-museum of the Salvi master weavers in Patan, witnessing the mathematical d...","Private Dawn Exploration of Rani ki Vav & Modhera Sun Temple: Curator-led private dawn visit to the UNESCO stepwell of Rani ki Vav and the Modhera Sun Temple before public ..."]$$::jsonb,
    $$["/images/destinations/gujarat/hero.jpg","/images/destinations/gujarat/modhera-sun-temple.jpg","/images/destinations/gujarat/gir-asiatic-lion.jpg","/images/destinations/gujarat/rani-ki-vav.jpg","/images/destinations/gujarat/hotel-aramness-gir.jpg","/images/destinations/gujarat/hotel-rann-luxury-camp.jpg"]$$::jsonb,
    true
  ),
(
    'sikkim-darjeeling',
    'Sikkim & Darjeeling Eastern Himalayas',
    'Himalayas & Ladakh',
    $$Planter Tea Terroirs, Sacred Kanchenjunga & Ancient Nyingma Gompas$$,
    '/images/destinations/sikkim-darjeeling/hero.jpg',
    $$The Eastern Himalayas of Darjeeling and Sikkim rise in steep, mist-shrouded green terraces toward the third highest mountain on earth: Mount Kanchenjunga (8,586 m). Here, where Tibetan Buddhism meets British colonial hill-station heritage, the air is scented with woodsmoke, mountain pine, and the fragrant, floral aroma of freshly plucked tea leaves.$$,
    $$March to May (Himalayan Spring / Orchid & Blossom Season - prime touring climate)$$,
    $$12°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Kanchenjunga Viewing & Planter's High Tea at Glenburn: Private sunrise tea service on the Simbong terrace of Glenburn Tea Estate, watching the dawn sunlight turn the...","Master Tea Taster Workshop & Plucking Masterclass, Glenburn: Private walking masterclass through the tea gardens with the estate manager, learning the delicate art of harv...","Private Steam Train Charter on the UNESCO Darjeeling Himalayan Railway: Private chartered steam locomotive ride aboard the historic 1881 \"Toy Train\" from Darjeeling to Ghoom, passing...","Private Monastic Puja & Blessing at Pemayangtse Monastery: Private dawn prayer ceremony inside the 18th-century prayer hall of Pemayangtse Gompa, receiving a silk ceremo...","Curator Tour of the Golden Stupa & Sacred Art Relics at Rumtek: Private guided exploration of Rumtek Monastery and its sacred art collection with a resident scholar of Buddhi..."]$$::jsonb,
    $$["/images/destinations/sikkim-darjeeling/hero.jpg","/images/destinations/sikkim-darjeeling/glenburn-tea-estate.jpg","/images/destinations/sikkim-darjeeling/kanchenjunga-dawn.jpg","/images/destinations/sikkim-darjeeling/rumtek-monastery.jpg"]$$::jsonb,
    true
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  tagline = EXCLUDED.tagline,
  hero_image = EXCLUDED.hero_image,
  description = EXCLUDED.description,
  best_time_to_visit = EXCLUDED.best_time_to_visit,
  weather_info = EXCLUDED.weather_info,
  ideal_duration = EXCLUDED.ideal_duration,
  highlights = EXCLUDED.highlights,
  gallery = EXCLUDED.gallery,
  is_featured = EXCLUDED.is_featured; they stroll through the stone courtyards of abandoned medieval mosques, rest beside ancient banyan-draped cenotaphs, and hunt sambar deer along the shores of lotus-carpeted lakes.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$15°C - 27°C Day / 7°C - 12°C Night$$,
    $$4 to 6 Days$$,
    $$["Private Open-Top 4x4 Safari across Core Zones 1 to 5: Exclusive morning and afternoon game drives in customized open 4x4 safari vehicles accompanied by a master tra...","Sunset Champagne Walk atop Ranthambore Fort: Private guided ascent through the monumental gateways of the 10th-century fortress with a heritage scholar, en...","Private River Safari on the National Chambal Sanctuary: Private chartered boat expedition along the protected waters of the Chambal River, guided by a herpetologist t...","Naturalist Storytelling & Photography Masterclass at SUJÁN Sher Bagh: Intimate fireside masterclass with an award-winning wildlife photographer and tracker, reviewing high-speed ca...","Dawn Birding & Wilderness Walk around Mansarovar & Surwal Lakes: Private dawn walking expedition with a specialist ornithologist around local freshwater lakes, spotting thousa..."]$$::jsonb,
    $$["/images/destinations/ranthambore/hero.jpg","/images/destinations/ranthambore/tiger-stalking-banyan.jpg","/images/destinations/ranthambore/ranthambore-hill-fort.jpg","/images/destinations/ranthambore/chambal-sanctuary.jpg","/images/destinations/ranthambore/hotel-sujan-sher-bagh.jpg","/images/destinations/ranthambore/hotel-oberoi-vanyavilas.jpg"]$$::jsonb,
    true
  ),
(
    'goa',
    'Goa & Portuguese Heritage Coast',
    'Western India',
    $$Colonial Mansions, Private Catamarans & Coastal Haute Cuisine$$,
    '/images/destinations/goa/hero.jpg',
    $$Goa is defined by a gentle, tropical rhythm born from four and a half centuries of Portuguese maritime dominion along the sun-drenched Konkan coast. Quite distinct from the rest of the Indian subcontinent, the spirit of Goa - captured in the local philosophy of *susegad* (a relaxed, contented state of mind) - is felt in the rustle of coconut palm fronds, the tolling of white church bells across emerald paddy fields, and the salty breeze blowing in from the Arabian Sea.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$22°C - 32°C Day / 18°C - 22°C Night$$,
    $$5 to 8 Days$$,
    $$["Private Sunset Charter aboard a Luxury Catamaran, Mandovi Estuary: Private yacht or catamaran charter navigating from the Mandovi River out into Aguada Bay, accompanied by chill...","Architectural Walking Salon in Fontainhas with a Conservation Scholar: Private guided walk through the Latin Quarter with a renowned Indo-Portuguese architectural preservationist, g...","Private After-Hours Exploration of the Basilica of Bom Jesus, Old Goa: Exclusive after-hours access to the sacred sanctuaries and sacristy of the UNESCO-listed Basilica of Bom Jesus...","Artisanal Feni Distillation Masterclass on a Heritage Cashew Plantation: Private excursion to a secluded family-owned estate in Valpoi or Ponda, observing traditional wood-fired coppe...","Private Dolphin & Secret Cove Yacht Cruise to the Grand Island Reefs: Morning yacht excursion around the headlands of Cabo de Rama and Grand Island, tracking Indo-Pacific humpback ..."]$$::jsonb,
    $$["/images/destinations/goa/hero.jpg","/images/destinations/goa/fontainhas-latin-quarter.jpg","/images/destinations/goa/heritage-portuguese-mansion.jpg","/images/destinations/goa/private-catamaran-sunset.jpg","/images/destinations/goa/secluded-cove-sunset.jpg","/images/destinations/goa/hotel-taj-exotica.jpg"]$$::jsonb,
    true
  ),
(
    'kashmir',
    'Kashmir & The Vale of Srinagar',
    'Himalayas & Ladakh',
    $$Mughal Garden Terraces, Cedar Houseboats & Alpine Splendor$$,
    '/images/destinations/kashmir/hero.jpg',
    $$Framed by the snow-crowned amphitheatre of the Pir Panjal and Great Himalayan ranges, the Vale of Kashmir has been celebrated for centuries as heaven on earth (*Firdaus bar roo-ye zameen*). At the heart of this high-altitude basin lies Srinagar, a city organized around the aquatic poetry of Dal and Nigeen Lakes. Here, morning mist rises from still waters like spun silk, revealing hundreds of intricately carved cedar-wood houseboats, their Victorian fretwork reflected in mirror-smooth water lilies.$$,
    $$March to May (Spring Blossom & Tulip Radiance - prime touring climate)$$,
    $$10°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Private Cedar Shikara to the Floating Dawn Market: Private morning navigation aboard a luxury cedar shikara across mist-covered Dal Lake to the 200-year-old floa...","Curator-Led Architectural Walk of Shalimar & Nishat Mughal Gardens: Private after-hours exploration of the Mughal pleasure gardens with an architectural historian, examining the ...","Hangul Deer Tracking Expedition in Dachigam National Park: Exclusive morning wildlife safari in Dachigam National Park with a senior wildlife biologist, tracking the cri...","Master Atelier Visit: Authentic Kani & Sozni Pashmina Guilds: Behind-the-scenes access to a multigenerational family karkhana (workshop) in the Old City of Srinagar, observ...","Helicopter Flight & Gondola Ascent to Apharwat Peak, Gulmarg: Private helicopter transfer to Gulmarg, followed by VIP skip-the-line boarding on the Gulmarg Gondola to Aphar..."]$$::jsonb,
    $$["/images/destinations/kashmir/hero.jpg","/images/destinations/kashmir/dal-lake-shikara.jpg","/images/destinations/kashmir/mughal-gardens.jpg","/images/destinations/kashmir/gulmarg-himalayas.jpg","/images/destinations/kashmir/kashmir-shikara-floating.jpg"]$$::jsonb,
    true
  ),
(
    'central-india',
    'Central India & Khajuraho Heritage Corridor',
    'Central India',
    $$Medieval Dynastic Temples, River Cenotaphs & Sovereign Tiger Forests$$,
    '/images/destinations/central-india/hero.jpg',
    $$The Central Indian heritage corridor encompasses a majestic cross-section of Indian antiquity. Stretching from the sandstone temple hills of Khajuraho across the medieval fortresses of Orchha to the dense sal forests of Bandhavgarh and Kanha, this is a realm where the boundary between human artistry and primeval nature dissolves entirely.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$10°C - 26°C Day / 4°C - 10°C Night$$,
    $$6 to 9 Days$$,
    $$["Private Sunrise Architectural Tour of the Western Group of Khajuraho: Private, early morning access to the Kandariya Mahadeva and Lakshmana temples with a senior archaeological sch...","Twilight Flute & Sitar Salon at the Orchha Cenotaphs on the River Betwa: Private candlelit reception on the banks of the Betwa River directly facing the illuminated Bundela cenotaphs,...","Private Core-Zone Tiger Tracking in Bandhavgarh with Master Naturalists: Full-day private safari permit across the Tala and Magdhi core zones in an open 4x4 safari vehicle, tracking t...","Dawn Barasingha Safari across Kanha's Maiden Grasslands: Morning game drive across the mist-covered central meadows of Kanha, observing the rare hard-ground barasingha...","Private River Safari on the Ken River Canyon, Panna: Boat expedition through the deep sandstone gorges of the Ken River inside Panna Tiger Reserve, observing nesti..."]$$::jsonb,
    $$["/images/destinations/central-india/hero.jpg","/images/destinations/central-india/khajuraho-temple.jpg","/images/destinations/central-india/orchha-cenotaphs.jpg","/images/destinations/central-india/bandhavgarh-tiger.jpg"]$$::jsonb,
    true
  ),
(
    'tamil-nadu',
    'Tamil Nadu & The Great Living Chola Temples',
    'South India',
    $$Imperial Granite Vimanas, Merchant Palaces & Sacred Classical Arts$$,
    '/images/destinations/tamil-nadu/hero.jpg',
    $$Tamil Nadu is the guardian of unbroken Dravidian civilization. Unlike northern realms whose architectural monuments were repeatedly reshaped by successive waves of conquest, the Cauvery Delta and southern plains of Tamil Nadu have preserved their classical language, ritual temple architecture, and philosophical traditions for more than two millennia. This is an empire of monumental granite, where soaring temple towers (*gopurams*) encrusted with thousands of painted deities dominate the palm-fringed horizon.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$20°C - 30°C$$,
    $$7 to 10 Days$$,
    $$["Private Pre-Dawn VIP Darshan at Brihadisvara Temple, Thanjavur: Curator-led private dawn access to the inner corridors and courtyards of the Great Chola Temple before public ...","Private Twilight Temple Procession at Madurai Meenakshi Temple: Exclusive VIP entry to witness the sacred night procession (*palliyarai*) at the Meenakshi Amman Temple, as th...","Architectural Exploration of Private Chettinad Mansions: Private walking tour of Kanadukathan and Kottaiyur led by a Chettinad heritage conservationist, gaining exclus...","Master Lost-Wax Bronze Casting Masterclass in Swamimalai: Private workshop visit to a 10th-generation master sthapathi family in Swamimalai, observing the creation of b...","Private Chamber Carnatic Veena or Vocal Recital: Intimate evening chamber concert inside the central courtyard of Visalam or Svatma, featuring renowned classic..."]$$::jsonb,
    $$["/images/destinations/tamil-nadu/hero.jpg","/images/destinations/tamil-nadu/thanjavur-temple.jpg","/images/destinations/tamil-nadu/madurai-meenakshi.jpg","/images/destinations/tamil-nadu/chettinad-mansion.jpg"]$$::jsonb,
    true
  ),
(
    'hampi',
    'Hampi & The Vijayanagara Imperial Ruins',
    'South India',
    $$Monolithic Granite Ruins, Mythic Boulders & Forgotten Empires$$,
    '/images/destinations/hampi/hero.jpg',
    $$Hampi exists in an otherworldly realm where human architectural ambition meets primeval geological fantasy. Spread across 4,000 hectares of rugged terrain in north-central Karnataka, the landscape is defined by millions of giant, rust-colored granite boulders precariously balanced across arid hillsides, bisected by the emerald currents of the sacred Tungabhadra River.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$16°C - 30°C$$,
    $$4 to 6 Days$$,
    $$["Private Coracle River Glide along the Tungabhadra at Dawn: Private sunrise excursion in a traditional wicker coracle boat across the quiet currents of the Tungabhadra, f...","Curator-Led Architectural Exploration of the Vittala Temple: Exclusive pre-opening access to the Vittala Temple complex with an epigraphist and architectural historian, ex...","Private Sunset Champagne Reception atop Malyavanta Hill: Private evening ascent to Malyavanta Raghunatha Temple or Hemakuta Hill, sipping chilled champagne on the warm...","Curated Expedition to the 6th-Century Rock Caves of Badami & Pattadakal: Private full-day excursion in a luxury SUV to the red sandstone cave temples of Badami and the UNESCO temples ...","Private Corbelled Bathing & Royal Court Dinner at Evolve Back: Multi-course imperial court dinner hosted on the private terrace of Kamalapura Palace, featuring royal Vijayan..."]$$::jsonb,
    $$["/images/destinations/hampi/hero.jpg","/images/destinations/hampi/virupaksha-temple.jpg","/images/destinations/hampi/tungabhadra-river.jpg","/images/destinations/hampi/hotel-evolve-back.jpg"]$$::jsonb,
    true
  ),
(
    'gujarat',
    'The White Desert & Royal Kingdoms of Gujarat',
    'Western India',
    $$White Salt Expanses, Asiatic Lions & Imperial Solanki Heritage$$,
    '/images/destinations/gujarat/hero.jpg',
    $$Gujarat is a land of luminous contrasts, where boundless desert wilderness meets centuries of mercantile wealth and imperial craftsmanship. Along the northern frontier lies the Great Rann of Kutch - the world's largest seasonal salt desert. Stretching toward the horizon in a blinding expanse of pure white salt crystals, this surreal landscape reflects the sky like a giant mirror. Under the light of a full moon, the Rann turns into a dreamscape of shimmering silver, home to semi-nomadic artisan communities whose vibrant hand-embroideries bring brilliant color to the barren earth.$$,
    $$October to March (Golden Winter / Salt Desert Season - prime touring climate)$$,
    $$12°C - 28°C Day / 8°C - 14°C Night$$,
    $$7 to 10 Days$$,
    $$["Full-Moon Midnight Excursion on the Great Rann of Kutch: Private evening expedition into the silent, white salt flats under the radiance of the full moon, accompanied ...","Private Open-Top 4x4 Asiatic Lion Safari in Gir National Park: Exclusive morning and evening game drives in Gir's core wildlife tracking zone led by a senior naturalist and ...","Masterclass with the Master of Rogan Art in Nirona: Private studio session in Nirona village with the Khatri family, observing the transformation of boiled castor...","Curator Salon at the Patan Patola Double-Ikat Silk Loom: Exclusive visit to the private home-museum of the Salvi master weavers in Patan, witnessing the mathematical d...","Private Dawn Exploration of Rani ki Vav & Modhera Sun Temple: Curator-led private dawn visit to the UNESCO stepwell of Rani ki Vav and the Modhera Sun Temple before public ..."]$$::jsonb,
    $$["/images/destinations/gujarat/hero.jpg","/images/destinations/gujarat/modhera-sun-temple.jpg","/images/destinations/gujarat/gir-asiatic-lion.jpg","/images/destinations/gujarat/rani-ki-vav.jpg","/images/destinations/gujarat/hotel-aramness-gir.jpg","/images/destinations/gujarat/hotel-rann-luxury-camp.jpg"]$$::jsonb,
    true
  ),
(
    'sikkim-darjeeling',
    'Sikkim & Darjeeling Eastern Himalayas',
    'Himalayas & Ladakh',
    $$Planter Tea Terroirs, Sacred Kanchenjunga & Ancient Nyingma Gompas$$,
    '/images/destinations/sikkim-darjeeling/hero.jpg',
    $$The Eastern Himalayas of Darjeeling and Sikkim rise in steep, mist-shrouded green terraces toward the third highest mountain on earth: Mount Kanchenjunga (8,586 m). Here, where Tibetan Buddhism meets British colonial hill-station heritage, the air is scented with woodsmoke, mountain pine, and the fragrant, floral aroma of freshly plucked tea leaves.$$,
    $$March to May (Himalayan Spring / Orchid & Blossom Season - prime touring climate)$$,
    $$12°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Kanchenjunga Viewing & Planter's High Tea at Glenburn: Private sunrise tea service on the Simbong terrace of Glenburn Tea Estate, watching the dawn sunlight turn the...","Master Tea Taster Workshop & Plucking Masterclass, Glenburn: Private walking masterclass through the tea gardens with the estate manager, learning the delicate art of harv...","Private Steam Train Charter on the UNESCO Darjeeling Himalayan Railway: Private chartered steam locomotive ride aboard the historic 1881 \"Toy Train\" from Darjeeling to Ghoom, passing...","Private Monastic Puja & Blessing at Pemayangtse Monastery: Private dawn prayer ceremony inside the 18th-century prayer hall of Pemayangtse Gompa, receiving a silk ceremo...","Curator Tour of the Golden Stupa & Sacred Art Relics at Rumtek: Private guided exploration of Rumtek Monastery and its sacred art collection with a resident scholar of Buddhi..."]$$::jsonb,
    $$["/images/destinations/sikkim-darjeeling/hero.jpg","/images/destinations/sikkim-darjeeling/glenburn-tea-estate.jpg","/images/destinations/sikkim-darjeeling/kanchenjunga-dawn.jpg","/images/destinations/sikkim-darjeeling/rumtek-monastery.jpg"]$$::jsonb,
    true
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  tagline = EXCLUDED.tagline,
  hero_image = EXCLUDED.hero_image,
  description = EXCLUDED.description,
  best_time_to_visit = EXCLUDED.best_time_to_visit,
  weather_info = EXCLUDED.weather_info,
  ideal_duration = EXCLUDED.ideal_duration,
  highlights = EXCLUDED.highlights,
  gallery = EXCLUDED.gallery,
  is_featured = EXCLUDED.is_featured; they stroll through the stone courtyards of abandoned medieval mosques, rest beside ancient banyan-draped cenotaphs, and hunt sambar deer along the shores of lotus-carpeted lakes.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$15°C - 27°C Day / 7°C - 12°C Night$$,
    $$4 to 6 Days$$,
    $$["Private Open-Top 4x4 Safari across Core Zones 1 to 5: Exclusive morning and afternoon game drives in customized open 4x4 safari vehicles accompanied by a master tra...","Sunset Champagne Walk atop Ranthambore Fort: Private guided ascent through the monumental gateways of the 10th-century fortress with a heritage scholar, en...","Private River Safari on the National Chambal Sanctuary: Private chartered boat expedition along the protected waters of the Chambal River, guided by a herpetologist t...","Naturalist Storytelling & Photography Masterclass at SUJÁN Sher Bagh: Intimate fireside masterclass with an award-winning wildlife photographer and tracker, reviewing high-speed ca...","Dawn Birding & Wilderness Walk around Mansarovar & Surwal Lakes: Private dawn walking expedition with a specialist ornithologist around local freshwater lakes, spotting thousa..."]$$::jsonb,
    $$["/images/destinations/ranthambore/hero.jpg","/images/destinations/ranthambore/tiger-stalking-banyan.jpg","/images/destinations/ranthambore/fort-ruins-jungle.jpg"]$$::jsonb,
    true
  ),
(
    'goa',
    'Goa & Portuguese Heritage Coast',
    'Western India',
    $$Colonial Mansions, Private Catamarans & Coastal Haute Cuisine$$,
    '/images/destinations/goa/hero.jpg',
    $$Goa is defined by a gentle, tropical rhythm born from four and a half centuries of Portuguese maritime dominion along the sun-drenched Konkan coast. Quite distinct from the rest of the Indian subcontinent, the spirit of Goa - captured in the local philosophy of *susegad* (a relaxed, contented state of mind) - is felt in the rustle of coconut palm fronds, the tolling of white church bells across emerald paddy fields, and the salty breeze blowing in from the Arabian Sea.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$22°C - 32°C Day / 18°C - 22°C Night$$,
    $$5 to 8 Days$$,
    $$["Private Sunset Charter aboard a Luxury Catamaran, Mandovi Estuary: Private yacht or catamaran charter navigating from the Mandovi River out into Aguada Bay, accompanied by chill...","Architectural Walking Salon in Fontainhas with a Conservation Scholar: Private guided walk through the Latin Quarter with a renowned Indo-Portuguese architectural preservationist, g...","Private After-Hours Exploration of the Basilica of Bom Jesus, Old Goa: Exclusive after-hours access to the sacred sanctuaries and sacristy of the UNESCO-listed Basilica of Bom Jesus...","Artisanal Feni Distillation Masterclass on a Heritage Cashew Plantation: Private excursion to a secluded family-owned estate in Valpoi or Ponda, observing traditional wood-fired coppe...","Private Dolphin & Secret Cove Yacht Cruise to the Grand Island Reefs: Morning yacht excursion around the headlands of Cabo de Rama and Grand Island, tracking Indo-Pacific humpback ..."]$$::jsonb,
    $$["/images/destinations/goa/hero.jpg","/images/destinations/goa/fontainhas-latin-quarter.jpg","/images/destinations/goa/heritage-portuguese-mansion.jpg","/images/destinations/goa/private-catamaran-sunset.jpg","/images/destinations/goa/secluded-cove-sunset.jpg"]$$::jsonb,
    true
  ),
(
    'kashmir',
    'Kashmir & The Vale of Srinagar',
    'Himalayas & Ladakh',
    $$Mughal Garden Terraces, Cedar Houseboats & Alpine Splendor$$,
    '/images/destinations/kashmir/hero.jpg',
    $$Framed by the snow-crowned amphitheatre of the Pir Panjal and Great Himalayan ranges, the Vale of Kashmir has been celebrated for centuries as heaven on earth (*Firdaus bar roo-ye zameen*). At the heart of this high-altitude basin lies Srinagar, a city organized around the aquatic poetry of Dal and Nigeen Lakes. Here, morning mist rises from still waters like spun silk, revealing hundreds of intricately carved cedar-wood houseboats, their Victorian fretwork reflected in mirror-smooth water lilies.$$,
    $$March to May (Spring Blossom & Tulip Radiance - prime touring climate)$$,
    $$10°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Private Cedar Shikara to the Floating Dawn Market: Private morning navigation aboard a luxury cedar shikara across mist-covered Dal Lake to the 200-year-old floa...","Curator-Led Architectural Walk of Shalimar & Nishat Mughal Gardens: Private after-hours exploration of the Mughal pleasure gardens with an architectural historian, examining the ...","Hangul Deer Tracking Expedition in Dachigam National Park: Exclusive morning wildlife safari in Dachigam National Park with a senior wildlife biologist, tracking the cri...","Master Atelier Visit: Authentic Kani & Sozni Pashmina Guilds: Behind-the-scenes access to a multigenerational family karkhana (workshop) in the Old City of Srinagar, observ...","Helicopter Flight & Gondola Ascent to Apharwat Peak, Gulmarg: Private helicopter transfer to Gulmarg, followed by VIP skip-the-line boarding on the Gulmarg Gondola to Aphar..."]$$::jsonb,
    $$["/images/destinations/kashmir/hero.jpg","/images/destinations/kashmir/dal-lake-shikara.jpg","/images/destinations/kashmir/mughal-gardens.jpg","/images/destinations/kashmir/gulmarg-himalayas.jpg"]$$::jsonb,
    true
  ),
(
    'central-india',
    'Central India & Khajuraho Heritage Corridor',
    'Central India',
    $$Medieval Dynastic Temples, River Cenotaphs & Sovereign Tiger Forests$$,
    '/images/destinations/central-india/hero.jpg',
    $$The Central Indian heritage corridor encompasses a majestic cross-section of Indian antiquity. Stretching from the sandstone temple hills of Khajuraho across the medieval fortresses of Orchha to the dense sal forests of Bandhavgarh and Kanha, this is a realm where the boundary between human artistry and primeval nature dissolves entirely.$$,
    $$October to March (Golden Winter - prime touring climate)$$,
    $$10°C - 26°C Day / 4°C - 10°C Night$$,
    $$6 to 9 Days$$,
    $$["Private Sunrise Architectural Tour of the Western Group of Khajuraho: Private, early morning access to the Kandariya Mahadeva and Lakshmana temples with a senior archaeological sch...","Twilight Flute & Sitar Salon at the Orchha Cenotaphs on the River Betwa: Private candlelit reception on the banks of the Betwa River directly facing the illuminated Bundela cenotaphs,...","Private Core-Zone Tiger Tracking in Bandhavgarh with Master Naturalists: Full-day private safari permit across the Tala and Magdhi core zones in an open 4x4 safari vehicle, tracking t...","Dawn Barasingha Safari across Kanha's Maiden Grasslands: Morning game drive across the mist-covered central meadows of Kanha, observing the rare hard-ground barasingha...","Private River Safari on the Ken River Canyon, Panna: Boat expedition through the deep sandstone gorges of the Ken River inside Panna Tiger Reserve, observing nesti..."]$$::jsonb,
    $$["/images/destinations/central-india/hero.jpg","/images/destinations/central-india/khajuraho-temple.jpg","/images/destinations/central-india/orchha-cenotaphs.jpg","/images/destinations/central-india/bandhavgarh-tiger.jpg"]$$::jsonb,
    true
  ),
(
    'tamil-nadu',
    'Tamil Nadu & The Great Living Chola Temples',
    'South India',
    $$Imperial Granite Vimanas, Merchant Palaces & Sacred Classical Arts$$,
    '/images/destinations/tamil-nadu/hero.jpg',
    $$Tamil Nadu is the guardian of unbroken Dravidian civilization. Unlike northern realms whose architectural monuments were repeatedly reshaped by successive waves of conquest, the Cauvery Delta and southern plains of Tamil Nadu have preserved their classical language, ritual temple architecture, and philosophical traditions for more than two millennia. This is an empire of monumental granite, where soaring temple towers (*gopurams*) encrusted with thousands of painted deities dominate the palm-fringed horizon.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$20°C - 30°C$$,
    $$7 to 10 Days$$,
    $$["Private Pre-Dawn VIP Darshan at Brihadisvara Temple, Thanjavur: Curator-led private dawn access to the inner corridors and courtyards of the Great Chola Temple before public ...","Private Twilight Temple Procession at Madurai Meenakshi Temple: Exclusive VIP entry to witness the sacred night procession (*palliyarai*) at the Meenakshi Amman Temple, as th...","Architectural Exploration of Private Chettinad Mansions: Private walking tour of Kanadukathan and Kottaiyur led by a Chettinad heritage conservationist, gaining exclus...","Master Lost-Wax Bronze Casting Masterclass in Swamimalai: Private workshop visit to a 10th-generation master sthapathi family in Swamimalai, observing the creation of b...","Private Chamber Carnatic Veena or Vocal Recital: Intimate evening chamber concert inside the central courtyard of Visalam or Svatma, featuring renowned classic..."]$$::jsonb,
    $$["/images/destinations/tamil-nadu/hero.jpg","/images/destinations/tamil-nadu/thanjavur-temple.jpg","/images/destinations/tamil-nadu/madurai-meenakshi.jpg","/images/destinations/tamil-nadu/chettinad-mansion.jpg"]$$::jsonb,
    true
  ),
(
    'hampi',
    'Hampi & The Vijayanagara Imperial Ruins',
    'South India',
    $$Monolithic Granite Ruins, Mythic Boulders & Forgotten Empires$$,
    '/images/destinations/hampi/hero.jpg',
    $$Hampi exists in an otherworldly realm where human architectural ambition meets primeval geological fantasy. Spread across 4,000 hectares of rugged terrain in north-central Karnataka, the landscape is defined by millions of giant, rust-colored granite boulders precariously balanced across arid hillsides, bisected by the emerald currents of the sacred Tungabhadra River.$$,
    $$November to February (Golden Winter - prime touring climate)$$,
    $$16°C - 30°C$$,
    $$4 to 6 Days$$,
    $$["Private Coracle River Glide along the Tungabhadra at Dawn: Private sunrise excursion in a traditional wicker coracle boat across the quiet currents of the Tungabhadra, f...","Curator-Led Architectural Exploration of the Vittala Temple: Exclusive pre-opening access to the Vittala Temple complex with an epigraphist and architectural historian, ex...","Private Sunset Champagne Reception atop Malyavanta Hill: Private evening ascent to Malyavanta Raghunatha Temple or Hemakuta Hill, sipping chilled champagne on the warm...","Curated Expedition to the 6th-Century Rock Caves of Badami & Pattadakal: Private full-day excursion in a luxury SUV to the red sandstone cave temples of Badami and the UNESCO temples ...","Private Corbelled Bathing & Royal Court Dinner at Evolve Back: Multi-course imperial court dinner hosted on the private terrace of Kamalapura Palace, featuring royal Vijayan..."]$$::jsonb,
    $$["/images/destinations/hampi/hero.jpg","/images/destinations/hampi/stone-chariot.jpg","/images/destinations/hampi/virupaksha-temple.jpg","/images/destinations/hampi/tungabhadra-river.jpg"]$$::jsonb,
    true
  ),
(
    'gujarat',
    'The White Desert & Royal Kingdoms of Gujarat',
    'Western India',
    $$White Salt Expanses, Asiatic Lions & Imperial Solanki Heritage$$,
    '/images/destinations/gujarat/hero.jpg',
    $$Gujarat is a land of luminous contrasts, where boundless desert wilderness meets centuries of mercantile wealth and imperial craftsmanship. Along the northern frontier lies the Great Rann of Kutch - the world's largest seasonal salt desert. Stretching toward the horizon in a blinding expanse of pure white salt crystals, this surreal landscape reflects the sky like a giant mirror. Under the light of a full moon, the Rann turns into a dreamscape of shimmering silver, home to semi-nomadic artisan communities whose vibrant hand-embroideries bring brilliant color to the barren earth.$$,
    $$October to March (Golden Winter / Salt Desert Season - prime touring climate)$$,
    $$12°C - 28°C Day / 8°C - 14°C Night$$,
    $$7 to 10 Days$$,
    $$["Full-Moon Midnight Excursion on the Great Rann of Kutch: Private evening expedition into the silent, white salt flats under the radiance of the full moon, accompanied ...","Private Open-Top 4x4 Asiatic Lion Safari in Gir National Park: Exclusive morning and evening game drives in Gir's core wildlife tracking zone led by a senior naturalist and ...","Masterclass with the Master of Rogan Art in Nirona: Private studio session in Nirona village with the Khatri family, observing the transformation of boiled castor...","Curator Salon at the Patan Patola Double-Ikat Silk Loom: Exclusive visit to the private home-museum of the Salvi master weavers in Patan, witnessing the mathematical d...","Private Dawn Exploration of Rani ki Vav & Modhera Sun Temple: Curator-led private dawn visit to the UNESCO stepwell of Rani ki Vav and the Modhera Sun Temple before public ..."]$$::jsonb,
    $$["/images/destinations/gujarat/hero.jpg","/images/destinations/gujarat/rann-of-kutch.jpg","/images/destinations/gujarat/gir-asiatic-lion.jpg","/images/destinations/gujarat/modhera-sun-temple.jpg"]$$::jsonb,
    true
  ),
(
    'sikkim-darjeeling',
    'Sikkim & Darjeeling Eastern Himalayas',
    'Himalayas & Ladakh',
    $$Planter Tea Terroirs, Sacred Kanchenjunga & Ancient Nyingma Gompas$$,
    '/images/destinations/sikkim-darjeeling/hero.jpg',
    $$The Eastern Himalayas of Darjeeling and Sikkim rise in steep, mist-shrouded green terraces toward the third highest mountain on earth: Mount Kanchenjunga (8,586 m). Here, where Tibetan Buddhism meets British colonial hill-station heritage, the air is scented with woodsmoke, mountain pine, and the fragrant, floral aroma of freshly plucked tea leaves.$$,
    $$March to May (Himalayan Spring / Orchid & Blossom Season - prime touring climate)$$,
    $$12°C - 22°C$$,
    $$6 to 9 Days$$,
    $$["Dawn Kanchenjunga Viewing & Planter's High Tea at Glenburn: Private sunrise tea service on the Simbong terrace of Glenburn Tea Estate, watching the dawn sunlight turn the...","Master Tea Taster Workshop & Plucking Masterclass, Glenburn: Private walking masterclass through the tea gardens with the estate manager, learning the delicate art of harv...","Private Steam Train Charter on the UNESCO Darjeeling Himalayan Railway: Private chartered steam locomotive ride aboard the historic 1881 \"Toy Train\" from Darjeeling to Ghoom, passing...","Private Monastic Puja & Blessing at Pemayangtse Monastery: Private dawn prayer ceremony inside the 18th-century prayer hall of Pemayangtse Gompa, receiving a silk ceremo...","Curator Tour of the Golden Stupa & Sacred Art Relics at Rumtek: Private guided exploration of Rumtek Monastery and its sacred art collection with a resident scholar of Buddhi..."]$$::jsonb,
    $$["/images/destinations/sikkim-darjeeling/hero.jpg","/images/destinations/sikkim-darjeeling/glenburn-tea-estate.jpg","/images/destinations/sikkim-darjeeling/kanchenjunga-dawn.jpg","/images/destinations/sikkim-darjeeling/rumtek-monastery.jpg"]$$::jsonb,
    true
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  tagline = EXCLUDED.tagline,
  hero_image = EXCLUDED.hero_image,
  description = EXCLUDED.description,
  best_time_to_visit = EXCLUDED.best_time_to_visit,
  weather_info = EXCLUDED.weather_info,
  ideal_duration = EXCLUDED.ideal_duration,
  highlights = EXCLUDED.highlights,
  gallery = EXCLUDED.gallery,
  is_featured = EXCLUDED.is_featured;

-- SEED DATA: TOURS
-- =========================================================

INSERT INTO public.tours (slug, destination_name, title, subtitle, duration_days, duration_nights, price_usd, price_inr, activity_level, travel_style, group_type, is_featured, hero_image, overview, highlights, inclusions, exclusions)
VALUES
(
    'golden-triangle-royal-palaces',
    'Rajasthan',
    'The Royal Odyssey: Golden Triangle & Palaces of Udaipur',
    'An opulent journey through Delhi, Agra, Jaipur & the Lake City of Udaipur in true Maharaja style.',
    9,
    8,
    3850.00,
    320000.00,
    'Leisurely',
    'Heritage & Palaces',
    'Private Tailormade Journey',
    true,
    'https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?auto=format&fit=crop&w=1920&q=80',
    'Step into the timeless grandeur of royal India. From the Mughal monuments of Delhi and the ethereal ivory marble of the Taj Mahal at dawn to Jaipur pink palaces and Udaipur floating marble sanctuaries.',
    '["VIP sunrise viewing of Taj Mahal", "Exclusive high-tea in private Jaipur royal quarters", "Champagne sunset cruise on Lake Pichola", "Oberoi Amarvilas & Taj Lake Palace stays"]'::jsonb,
    '["8 nights in premier 5-star palace hotels", "Daily champagne breakfasts & 3 curated gourmet dinners", "Private chauffeur Mercedes E-Class/BMW", "All internal domestic flights in premium class", "Expert licensed academic historians"]'::jsonb,
    '["International airfare", "Indian tourist visa", "Travel insurance"]'::jsonb
),
(
    'kerala-backwaters-ayurveda-sanctuary',
    'Kerala & The Spice Coast',
    'Kerala Sanctuary: Private Houseboats, Spice Hills & Ayurvedic Bliss',
    'Immerse your senses in emerald tea plantations, private backwater cruises, and restorative holistic wellness.',
    8,
    7,
    3200.00,
    265000.00,
    'Leisurely',
    'Spiritual & Wellness',
    'Private Wellness Journey',
    true,
    'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1920&q=80',
    'Discover the serene pace of Southern India. Stroll colonial Fort Kochi, ascend misty Munnar tea hills, and cruise aboard private luxury houseboats.',
    '["2 nights aboard private luxury houseboat", "Doctor-prescribed daily Ayurvedic therapies", "Private Kathakali dance performance", "Single-estate tea tasting in Munnar"]'::jsonb,
    '["7 nights luxury retreats & private air-conditioned houseboat", "Private car & chauffeur throughout Kerala", "All meals on houseboat & wellness dining", "Full Ayurvedic regime"]'::jsonb,
    '["International flights", "Travel insurance"]'::jsonb
),
(
    'ladakh-high-himalayas-expedition',
    'Ladakh & High Himalayas',
    'Himalayan High Passes: Glacial Valleys, Monasteries & Luxury Glamping',
    'Venture into the mystical mountain desert of Ladakh, crossing the highest motorable roads on earth.',
    8,
    7,
    3450.00,
    285000.00,
    'Active Adventure',
    'Himalayan Exploration',
    'Private Expedition',
    true,
    'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1920&q=80',
    'An exhilarating high-comfort expedition across the Trans-Himalayan desert. Ancient monasteries, heated glamping domes, and turquoise Pangong Lake.',
    '["Morning blessing at Thiksey Gompa", "Crossing Khardung La Pass (17,582 ft) in 4x4 SUVs", "Heated luxury glamping at Hunder & Pangong", "Stargazing under Bortle Class 1 night skies"]'::jsonb,
    '["7 nights luxury hotels & heated glamping domes", "Private 4x4 Toyota Fortuner with Himalayan driver", "All expedition meals", "Inner Line & Wildlife permits"]'::jsonb,
    '["International airfare", "Thermal outerwear"]'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Done!
