import { Destination } from '@/types';

export const mockDestinations: Destination[] = [
  {
    id: 'dest-1',
    slug: 'rajasthan',
    name: 'Rajasthan',
    region: 'North India',
    tagline: 'Fortress Citadels, Lake Palaces & Living Royal Heritage',
    hero_image: '/images/destinations/rajasthan/hero.jpg',
    description:
      'From the 16th-century hill forts of the Aravallis to the island palaces of Lake Pichola, Rajasthan preserves centuries of Rajput and Mughal architecture. Daily life moves between walled bazaar lanes and quiet palace courtyards, where craft traditions like hand-block printing, stone inlay, and miniature painting continue uninterrupted.',
    best_time_to_visit: 'October to March (Pleasant winter climate, ideal for cultural touring and desert excursions)',
    weather_info: '20°C - 28°C Day / 10°C - 15°C Night',
    ideal_duration: '7 to 12 Days',
    highlights: [
      'Private sunset cruise aboard a ceremonial royal barge on Lake Pichola, Udaipur',
      'Exclusive curator-led access to the private Chandra Mahal suites in Jaipur City Palace',
      'Dawn private viewing of the Taj Mahal and Mughal fortresses with architectural scholars',
      'Excursion to the 15th-century Ranakpur temple and its 1,444 carved marble pillars',
    ],
    gallery: [
      '/images/destinations/rajasthan/hero.jpg',
      '/images/destinations/rajasthan/jaipur-hawa-mahal.jpg',
      '/images/destinations/rajasthan/udaipur-lake-palace.jpg',
      '/images/destinations/rajasthan/jodhpur-blue-city.jpg',
    ],
    is_featured: true,
  },
  {
    id: 'dest-2',
    slug: 'kerala',
    name: 'Kerala & The Spice Coast',
    region: 'South India',
    tagline: 'Spice Plantations, Backwater Canals & Classical Ayurveda',
    hero_image: '/images/destinations/kerala/hero.jpg',
    description:
      'From the 16th-century trading ports of Fort Kochi to the high tea estates of Munnar and the slow-moving canals of Alleppey, Kerala offers a calm, waterborne way of traveling. Days are defined by private Kettuvallam houseboat cruises, organic spice walks, and classical Ayurvedic therapies along the shores of Lake Vembanad.',
    best_time_to_visit: 'September to April (Pleasant post-monsoon climate, ideal for backwater cruising and plantation walks)',
    weather_info: '24°C - 30°C Tropical & Coastal',
    ideal_duration: '6 to 10 Days',
    highlights: [
      'Private chartered Kettuvallam houseboat cruise along the Alleppey canals',
      'Single-estate tea and cardamom walks in the Western Ghats at Munnar',
      'Doctor-guided classical Ayurvedic treatments at Kumarakom on Lake Vembanad',
      'Private Kathakali performance with access to the green-room makeup ritual',
    ],
    gallery: [
      '/images/destinations/kerala/hero.jpg',
      '/images/destinations/kerala/alleppey-houseboat.jpg',
      '/images/destinations/kerala/munnar-tea-plantations.jpg',
      '/images/destinations/kerala/kochi-chinese-nets.jpg',
    ],
    is_featured: true,
  },
  {
    id: 'dest-3',
    slug: 'ladakh',
    name: 'Ladakh & High Himalayas',
    region: 'Himalayas & Ladakh',
    tagline: 'High-Altitude Monasteries, Glacial Passes & Silk Road Valleys',
    hero_image: '/images/destinations/ladakh/hero.jpg',
    description:
      'Set between the Karakoram and Great Himalaya ranges at elevations above 11,000 feet, Ladakh is defined by ancient Tibetan Buddhist gompas, high mountain passes, and cold-desert valleys. Journeys move between 17th-century mountain citadels in Leh, sand dunes in Nubra, and the shores of Pangong Tso.',
    best_time_to_visit: 'May to September (Clear mountain roads, sunny days, and vibrant monastery festivals)',
    weather_info: '12°C - 22°C Day / 2°C - 8°C Crisp Mountain Night',
    ideal_duration: '7 to 10 Days',
    highlights: [
      'Pre-dawn prayer puja with copper horns and butter lamps at Thiksey Monastery',
      'Drive across the 17,582-foot Khardung La pass in private heated 4x4 vehicles',
      'Heated yurt glamping along the shores of Pangong Tso at 14,270 feet',
      'Cultural exploration of Turtuk and the 11th-century murals at Alchi',
    ],
    gallery: [
      '/images/destinations/ladakh/hero.jpg',
      '/images/destinations/ladakh/pangong-lake-azure.jpg',
      '/images/destinations/ladakh/thiksey-monastery.jpg',
    ],
    is_featured: true,
  },
  {
    id: 'dest-4',
    slug: 'varanasi',
    name: 'Varanasi & Sacred Ganges',
    region: 'North India',
    tagline: 'Riverfront Rituals, Classical Heritage & Sacred Antiquity',
    hero_image: '/images/destinations/varanasi/hero.jpg',
    description:
      'Built along the sweeping northern bend of the Ganges, Varanasi has maintained an unbroken daily rhythm along its 84 stone ghats for nearly three millennia. Dawn wooden boat rides and evening Aarti rituals anchor a city renowned for master silk weaving, classical music, and the early Buddhist heritage of nearby Sarnath.',
    best_time_to_visit: 'October to March',
    weather_info: '18°C - 26°C Pleasant & Mild',
    ideal_duration: '3 to 5 Days',
    highlights: [
      'Dawn wooden bajra boat ride along the 84 ghats with classical raga musicians',
      'Front-row boat mooring and private rooftop vantage for the evening Ganga Aarti',
      'Master silk weavers workshop visits in Madanpura for pure Katan and zari brocades',
      'Excursion to Sarnath, visiting the 5th-century Dhamek Stupa and Ashoka Lion Capital',
    ],
    gallery: [
      '/images/destinations/varanasi/hero.jpg',
      '/images/destinations/varanasi/sunrise-boat-ghats.jpg',
      '/images/destinations/varanasi/evening-ganga-aarti.jpg',
    ],
    is_featured: false,
  },
  {
    id: 'dest-5',
    slug: 'ranthambore',
    name: 'Ranthambore & Royal Wilds',
    region: 'Central India',
    tagline: 'Private Bengal Tiger Safaris in Ancient Jungle Ruins',
    hero_image: '/images/destinations/ranthambore/hero.jpg',
    description:
      'Spanning 1,334 square kilometers of dry deciduous forest and rocky escarpments in southeastern Rajasthan, Ranthambore centers around a 10th-century hilltop fortress where tigers roam among ancient chattris and banyan trees. Game drives into core zones with veteran naturalists track Bengal tigers, leopards, and sloth bears, while the nearby Chambal River sanctuary preserves rare gharials and Ganges river dolphins.',
    best_time_to_visit: 'October to May (Best tiger sightings from February to April)',
    weather_info: '20°C - 32°C Forest & Dry Deciduous',
    ideal_duration: '4 to 6 Days',
    highlights: [
      'Private open-top 4x4 Gypsy game drives across Core Zones 1 to 5 with senior naturalists',
      'Boat expedition along the protected National Chambal Sanctuary for gharials and river dolphins',
      'Sunset guided walk through the 10th-century UNESCO World Heritage Ranthambore Hill Fort',
      'Luxury tented campaign living at Suján Sher Bagh or The Oberoi Vanyavilas with fireside dining',
    ],
    gallery: [
      '/images/destinations/ranthambore/hero.jpg',
      '/images/destinations/ranthambore/tiger-stalking-banyan.jpg',
      '/images/destinations/ranthambore/fort-ruins-jungle.jpg',
    ],
    is_featured: true,
  },
  {
    id: 'dest-6',
    slug: 'goa',
    name: 'Goa & The Portuguese Heritage Coast',
    region: 'Western India',
    tagline: 'Colonial Mansions, Private Catamarans & Coastal Haute Cuisine',
    hero_image: '/images/destinations/goa/hero.jpg',
    description:
      'Shaped by four centuries of Portuguese influence along the Konkan shoreline, Goa offers a distinctive blend of maritime history and tropical leisure. Private journeys explore the pastel-toned 18th-century Latin Quarter of Fontainhas, the baroque Manueline churches of Old Goa, and organic spice estates in the foothills of the Western Ghats, paired with secluded villa stays along Dolphin Bay and the white sands of Benaulim.',
    best_time_to_visit: 'October to April (Dry coastal breeze, calm seas, and pleasant evenings)',
    weather_info: '24°C - 31°C Coastal Tropical',
    ideal_duration: '5 to 7 Days',
    highlights: [
      'Private sunset charter aboard a luxury catamaran along the Mandovi and Zuari estuaries',
      'Architectural walking tour of Fontainhas Latin Quarter with a heritage conservation specialist',
      'Curator-led exploration of the UNESCO World Heritage cathedrals of Old Goa',
      'Stay in secluded private villa sanctuaries at Ahilya by the Sea and Taj Exotica Benaulim',
    ],
    gallery: [
      '/images/destinations/goa/hero.jpg',
      '/images/destinations/goa/fontainhas-latin-quarter.jpg',
      '/images/destinations/goa/private-catamaran-sunset.jpg',
      '/images/destinations/goa/taj-exotica-benaulim.jpg',
    ],
    is_featured: true,
  },
];
