import { Destination } from '@/types';

export const mockDestinations: Destination[] = [
  {
    id: 'dest-1',
    slug: 'rajasthan',
    name: 'Rajasthan',
    region: 'North India',
    tagline: 'Land of Maharajas, Desert Fortresses & Golden Opulence',
    hero_image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1920&q=80',
    description:
      'Immerse yourself in royal India. Rajasthan beckons with monumental sandstone forts, glistening marble lake palaces, private royal dining experiences, and kaleidoscopic desert dunes under starry skies.',
    best_time_to_visit: 'October to March (Pleasant winter climate, perfect for sightseeing and desert safaris)',
    weather_info: '20°C - 28°C Day / 10°C - 15°C Night',
    ideal_duration: '7 to 12 Days',
    highlights: [
      'Private sunset boat cruise on Lake Pichola, Udaipur',
      'Exclusive access to the City Palace private courtyards in Jaipur',
      'Desert glamping under starlit Thar skies with folk musicians',
      'Step-well dinners and vintage car transfers',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=1920&q=80',
    ],
    is_featured: true,
  },
  {
    id: 'dest-2',
    slug: 'kerala',
    name: 'Kerala & The Spice Coast',
    region: 'South India',
    tagline: "God's Own Country: Tranquil Backwaters, Tea Mist & Ayurvedic Sanctuary",
    hero_image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1920&q=80',
    description:
      'A serene contrast to the desert kingdoms. Glide down palm-fringed canals aboard ultra-luxurious private kettuvallam houseboats, wake to misty tea plantation panoramas in Munnar, and indulge in authentic traditional Ayurvedic therapies.',
    best_time_to_visit: 'September to April (Lush post-monsoon foliage and idyllic coastal breezes)',
    weather_info: '24°C - 30°C Tropical & Coastal',
    ideal_duration: '6 to 10 Days',
    highlights: [
      'Private luxury houseboat cruise through Alleppey backwaters',
      'Sensory spice plantation walks with master botanists',
      'Doctor-curated Ayurvedic wellness and rejuvenating body treatments',
      'Sunset Kathakali classical dance performances and private culinary sessions',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1920&q=80',
    ],
    is_featured: true,
  },
  {
    id: 'dest-3',
    slug: 'ladakh',
    name: 'Ladakh & High Himalayas',
    region: 'Himalayas & Ladakh',
    tagline: 'The Roof of the World: Glacial Valleys, Monasteries & Stargazing',
    hero_image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1920&q=80',
    description:
      'A mythical mountain desert framed by 20,000-foot Himalayan peaks. Discover ancient Buddhist gompas perched on dramatic cliffs, azure high-altitude lakes, luxury dome camps in the Nubra Valley, and unpolluted nocturnal skies.',
    best_time_to_visit: 'May to September (Clear mountain roads, sunny days, vibrant monastery festivals)',
    weather_info: '12°C - 22°C Day / 2°C - 8°C Crisp Mountain Night',
    ideal_duration: '7 to 10 Days',
    highlights: [
      'Private blessings and morning chanting ceremonies at Thiksey Monastery',
      'Cross the Khardung La — one of the highest motorable mountain passes on Earth',
      'Luxury glamping with heated geodomes beside Pangong Tso Lake',
      'Night astronomy sessions with high-powered telescopes in high Ladakh',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?auto=format&fit=crop&w=1920&q=80',
    ],
    is_featured: true,
  },
  {
    id: 'dest-4',
    slug: 'varanasi',
    name: 'Varanasi & Sacred Ganges',
    region: 'North India',
    tagline: 'The Eternal Spiritual Heart of Ancient India',
    hero_image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1920&q=80',
    description:
      "Mark Twain described Varanasi as older than history, older than tradition. Experience the transcendent power of dawn boat rides along the sacred river ghats, mesmerizing evening Ganga Aarti fire rituals, and Sarnath's meditative Buddhist stupas.",
    best_time_to_visit: 'October to March',
    weather_info: '18°C - 26°C Pleasant & Mild',
    ideal_duration: '3 to 5 Days',
    highlights: [
      'Sunrise wooden boat glide along ancient river ghats with private historian',
      'VIP elevated seating for the nightly Dashashwamedh Ghat Ganga Aarti ceremony',
      'Private silk weavers atelier tour and tasting of royal Benarasi culinary delicacies',
      'Excursion to Sarnath where Lord Buddha delivered his first sermon',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1612865547334-09cb8cb455da?auto=format&fit=crop&w=1920&q=80',
    ],
    is_featured: false,
  },
  {
    id: 'dest-5',
    slug: 'ranthambore',
    name: 'Ranthambore & Royal Wilds',
    region: 'Central India',
    tagline: 'Private Bengal Tiger Safaris in Ancient Jungle Ruins',
    hero_image: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1920&q=80',
    description:
      'Where medieval fort ruins intertwine with the domain of the Royal Bengal Tiger. Experience exclusive 4x4 private safaris with elite naturalists, staying at ultra-luxurious safari tented camps inspired by royal hunting expeditions.',
    best_time_to_visit: 'October to May (Best tiger sightings from February to April)',
    weather_info: '20°C - 32°C Forest & Dry Deciduous',
    ideal_duration: '4 to 6 Days',
    highlights: [
      'Private customized open-top safari jeeps with veteran master trackers',
      'High-probability Royal Bengal Tiger, Leopard, and Sloth Bear tracking',
      'Sunset cocktails atop the 10th-century Ranthambore UNESCO World Heritage Fort',
      'Private royal bush dinners illuminated by hundreds of hurricane lanterns',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1562183667-a159d28118ec?auto=format&fit=crop&w=1920&q=80',
    ],
    is_featured: true,
  },
  {
    id: 'dest-6',
    slug: 'goa',
    name: 'Goa & The Portuguese Heritage Coast',
    region: 'Western India',
    tagline: 'Colonial Mansions, Private Catamarans & Coastal Haute Cuisine',
    hero_image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1920&q=80',
    description:
      'Far beyond ordinary beaches lies the storied Portuguese heritage of Goa. Discover restored 18th-century baroque mansions in Latin Quarters, private yacht charters along the Arabian Sea, and world-class Indo-Portuguese gastronomy.',
    best_time_to_visit: 'November to April (Balmy sunny days and vibrant ocean sunsets)',
    weather_info: '26°C - 31°C Tropical Breeze',
    ideal_duration: '4 to 7 Days',
    highlights: [
      'Private luxury catamaran sunset sail with champagne on the Mandovi River',
      'Curated heritage walk through Fontainhas Latin Quarter with local architect',
      'Fine-dining seaside experience paired with vintage feni and coastal seafood',
      'Stay in secluded 5-star private beachfront heritage estates',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1587922546307-776227941871?auto=format&fit=crop&w=1920&q=80',
    ],
    is_featured: false,
  },
];
