import { Inquiry } from '@/types';

export const mockInquiries: Inquiry[] = [
  {
    id: 'inq-101',
    tour_id: 'tour-1',
    tour_title: 'The Royal Odyssey: Golden Triangle & Palaces of Udaipur',
    traveler_name: 'Lord Henry Kensington',
    email: 'h.kensington@londonheritage.co.uk',
    phone: '+44 7700 900123',
    country: 'United Kingdom',
    departure_date: '2026-11-15',
    duration_days: 10,
    guests_count: 2,
    budget_tier: 'Ultra Luxury ($5k-$10k+)',
    travel_styles: ['Heritage & Palaces', 'Culinary & Culture'],
    special_requests:
      'Celebrating our 25th wedding anniversary. Interested in upgraded Presidential suites at Taj Lake Palace and a private vintage Rolls Royce transfer in Jaipur.',
    status: 'NEW',
    admin_notes: 'High-value anniversary lead. Check suite availability at Lake Palace for Nov 18-21.',
    created_at: '2026-08-18T14:30:00Z',
  },
  {
    id: 'inq-102',
    tour_id: 'tour-4',
    tour_title: 'The Sovereign Wild: Royal Bengal Tiger Safari & Jungle Lodges',
    traveler_name: 'Dr. Evelyn Reed',
    email: 'evelyn.reed@bioconserve.org',
    phone: '+1 (415) 890-4521',
    country: 'United States',
    departure_date: '2026-12-05',
    duration_days: 8,
    guests_count: 3,
    budget_tier: 'Premium Luxury ($3k-$5k)',
    travel_styles: ['Wildlife Safari'],
    special_requests:
      'Looking for top naturalist assignments in Zone 3 and Zone 4 in Ranthambore. Family of 3 including one teenager.',
    status: 'CONTACTED',
    admin_notes: 'Spoke via WhatsApp concierge. Sent draft itinerary with Oberoi Vanyavilas luxury tents.',
    created_at: '2026-08-16T09:15:00Z',
  },
  {
    id: 'inq-103',
    tour_id: 'tour-2',
    tour_title: 'Kerala Sanctuary: Private Houseboats, Spice Hills & Ayurvedic Bliss',
    traveler_name: 'Matthias & Sophie Weber',
    email: 'm.weber@zurichinvest.ch',
    phone: '+41 44 668 12 90',
    country: 'Switzerland',
    departure_date: '2026-10-20',
    duration_days: 9,
    guests_count: 2,
    budget_tier: 'Ultra Luxury ($5k-$10k+)',
    travel_styles: ['Spiritual & Wellness', 'Coastal & Luxury Stays'],
    special_requests:
      'Focused on intensive Ayurvedic rejuvenation. Require private master yoga instructor for morning sessions at Kumarakom.',
    status: 'PROPOSAL_SENT',
    admin_notes: 'Customized 9-day proposal with private 2-bedroom luxury houseboat sent. Follow-up scheduled for Friday.',
    created_at: '2026-08-14T11:45:00Z',
  },
  {
    id: 'inq-104',
    tour_id: undefined,
    tour_title: 'Custom Multi-City Itinerary (Rajasthan + Kerala)',
    traveler_name: 'Grace Tan',
    email: 'gracetan@singaporedesign.sg',
    phone: '+65 9123 4567',
    country: 'Singapore',
    departure_date: '2027-01-10',
    duration_days: 14,
    guests_count: 4,
    budget_tier: 'Custom Tailormade',
    travel_styles: ['Heritage & Palaces', 'Spiritual & Wellness', 'Culinary & Culture'],
    special_requests:
      'Group of 4 friends. Want 7 days in Rajasthan (Udaipur & Jodhpur) followed by 7 days in Kerala backwaters and Cochin spice art galleries.',
    status: 'CONFIRMED',
    admin_notes: 'Deposit received. Private chauffeurs and domestic flights confirmed with Taj & Oberoi properties.',
    created_at: '2026-08-10T16:20:00Z',
  },
];
