import { Tour } from '@/types';

export const mockTours: Tour[] = [
  {
    id: 'tour-1',
    slug: 'golden-triangle-royal-palaces',
    destination_id: 'dest-1',
    destination_name: 'Rajasthan',
    title: 'The Royal Odyssey: Golden Triangle & Palaces of Udaipur',
    subtitle: 'An opulent journey through Delhi, Agra, Jaipur & the Lake City of Udaipur in true Maharaja style.',
    duration_days: 9,
    duration_nights: 8,
    price_usd: 3850,
    price_inr: 320000,
    activity_level: 'Leisurely',
    travel_style: 'Heritage & Palaces',
    group_type: 'Private Tailormade Journey',
    is_featured: true,
    hero_image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1920&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1920&q=80',
    ],
    overview:
      'Step into the timeless grandeur of royal India. From the majestic Mughal domes of Delhi and the ethereal ivory marble of the Taj Mahal at sunrise to the rose-pink courtyards of Jaipur and the fairytale floating palaces of Lake Pichola. Enjoy private chauffeur-driven luxury sedans, premier heritage palace suites, skip-the-line VIP entrances, and dinners hosted in private royal quarters.',
    highlights: [
      'VIP sunrise private viewing of the Taj Mahal with expert architectural historian',
      'Exclusive high-tea in the private living quarters of the Jaipur Royal Family',
      'Champagne sunset cruise aboard a royal barge on Lake Pichola, Udaipur',
      'Stay in world-renowned palace hotels: The Oberoi Amarvilas & Taj Lake Palace',
      'Private culinary masterclass with a royal Rajasthani chef in a restored haveli',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in New Delhi – The Grand Welcome',
        location: 'Delhi',
        description:
          'Arrive at Indira Gandhi International Airport where your private airport concierge greets you at the jet bridge and whisks you through VIP immigration. Transfer in a private luxury chauffeur-driven Mercedes to The Imperial, New Delhi. Unwind with an evening welcome cocktail in the historic 1911 Bar.',
        stay: 'The Imperial, New Delhi (Heritage Suite)',
        meals: 'Dinner Included',
        highlights: ['VIP Airport Fast-Track', 'Welcome Champagne'],
        image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1920&q=80',
      },
      {
        day: 2,
        title: 'Imperial Delhi: Monuments of Empires',
        location: 'Delhi',
        description:
          'Explore Old Delhi’s labyrinthine bazaars via custom vintage rickshaw, visiting the Jama Masjid and the Red Fort. In the afternoon, transition to the grand tree-lined avenues of Lutyens’ New Delhi, visiting Humayun’s Tomb and Qutub Minar with your private historian guide.',
        stay: 'The Imperial, New Delhi',
        meals: 'Breakfast & Gourmet Lunch',
        highlights: ['Private Rickshaw Spice Market Safari', 'UNESCO Heritage Monuments'],
      },
      {
        day: 3,
        title: 'Agra – The Monument to Eternal Love',
        location: 'Agra',
        description:
          'Travel in comfort along the Yamuna Expressway to Agra. Check into The Oberoi Amarvilas, where every single room enjoys uninterrupted views of the Taj Mahal. In the late afternoon, witness the sunset over the Taj Mahal from the lush Mehtab Bagh gardens across the river.',
        stay: 'The Oberoi Amarvilas, Agra (Premier Room with Taj View)',
        meals: 'Breakfast & Dinner',
        highlights: ['Uninterrupted Taj Mahal views from private balcony', 'Sunset riverbank viewpoint'],
        image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1920&q=80',
      },
      {
        day: 4,
        title: 'Sunrise at Taj Mahal & Royal Agra Fort',
        location: 'Agra to Jaipur',
        description:
          'Enter the Taj Mahal at dawn before the crowds arrive. Watch the morning sun bathe the white marble in warm pink and amber hues. After a lavish breakfast, explore the royal pavilions of Agra Fort before embarking on the scenic drive to Jaipur, stopping at the stunning 9th-century Chand Baori stepwell in Abhaneri.',
        stay: 'The Rambagh Palace, Jaipur (Palace Room)',
        meals: 'Breakfast & Traditional Lunch',
        highlights: ['Sunrise Taj Mahal Experience', 'Abhaneri Stepwell Exploration'],
      },
      {
        day: 5,
        title: 'Jaipur – The Pink City & Amber Fort in Royal Splendor',
        location: 'Jaipur',
        description:
          'Ascend to the hilltop Amber Fort for an exclusive tour of the Sheesh Mahal (Mirror Palace). Return to the city to visit the Hawa Mahal (Palace of Winds), the royal Jantar Mantar astronomical observatory, and the opulent City Palace, culminating in an exclusive afternoon high-tea in the private royal apartments.',
        stay: 'The Rambagh Palace, Jaipur',
        meals: 'Breakfast & High-Tea Dinner',
        highlights: ['Amber Fort VIP Access', 'Private Royal Family Quarters High-Tea'],
        image: 'https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?auto=format&fit=crop&w=1920&q=80',
      },
      {
        day: 6,
        title: 'Jaipur to Udaipur – The Venice of the East',
        location: 'Jaipur to Udaipur',
        description:
          'Board a short luxury flight or private transfer to Udaipur. Arrive at the iconic Taj Lake Palace, floating majestically in the middle of Lake Pichola. Check in via private royal boat transfer with rose-petal blessings. Relax by the marble pool as the sun dips behind the Aravalli Hills.',
        stay: 'Taj Lake Palace, Udaipur (Lake View Luxury Room)',
        meals: 'Breakfast & Candlelight Dinner',
        highlights: ['Royal Boat Transfer', 'Iconic Floating Palace Experience'],
      },
      {
        day: 7,
        title: 'Udaipur – City Palace & Sunset Royal Barge Cruise',
        location: 'Udaipur',
        description:
          'Tour the sprawling Udaipur City Palace complex overlooking the lake. Browse artisan miniature painting studios with a master craftsman. In the evening, step aboard a 150-year-old ceremonial royal barge for a private sunset champagne cruise past Jag Mandir Island.',
        stay: 'Taj Lake Palace, Udaipur',
        meals: 'Breakfast & Royal Barge Drinks',
        highlights: ['Udaipur City Palace', 'Private Royal Barge Sunset Cruise'],
        image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1920&q=80',
      },
      {
        day: 8,
        title: 'Rural Udaipur & Vintage Car Sanctuary',
        location: 'Udaipur',
        description:
          'Drive into the surrounding Aravalli countryside for a leisurely walk through local villages and organic spice farms. Visit the Mewar Royal Vintage Car collection followed by a private lakeside farewell gala dinner with live Sufi musicians.',
        stay: 'Taj Lake Palace, Udaipur',
        meals: 'Breakfast & Gala Farewell Dinner',
        highlights: ['Rural Countryside Immersion', 'Lakeside Gala Dinner with Live Sufi Music'],
      },
      {
        day: 9,
        title: 'Farewell Udaipur & Onward Journey',
        location: 'Udaipur / Delhi',
        description:
          'Enjoy a leisurely champagne breakfast on the palace terrace. Transfer to Maharana Pratap Airport with full concierge assistance for your domestic connection to Delhi/Mumbai and onward international flight home.',
        stay: 'Departure',
        meals: 'Breakfast',
        highlights: ['Private Airport Transfer & Concierge Support'],
      },
    ],
    inclusions: [
      '8 nights accommodation in premier 5-star palace hotels (The Imperial, Oberoi Amarvilas, Rambagh Palace, Taj Lake Palace)',
      'Daily lavish champagne breakfasts, 3 curated private gourmet dinners, and afternoon high-teas',
      'Private air-conditioned luxury sedan (Mercedes E-Class or BMW) with experienced English-speaking chauffeur',
      'All internal domestic flights in premium class (Jaipur/Delhi to Udaipur)',
      'Dedicated expert licensed academic historians and local guides in each city',
      'All monument VIP entrance fees, camera permissions, and boat charters',
      '24/7 dedicated ABC Travels Senior Concierge on call throughout your journey',
    ],
    exclusions: [
      'International flights to/from India',
      'Indian tourist visa fees (available as eVisa)',
      'Travel insurance and medical coverage',
      'Personal discretionary expenses and gratuities',
    ],
    accommodations: [
      {
        name: 'The Imperial, New Delhi',
        location: 'Janpath, New Delhi',
        tier: '5-Star Heritage Landmark',
        image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1920&q=80',
        description: 'Voted India’s best luxury heritage hotel, combining Victorian charm with art deco elegance.',
      },
      {
        name: 'The Oberoi Amarvilas, Agra',
        location: 'Agra (600m from Taj Mahal)',
        tier: 'Ultra-Luxury Resort',
        image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1920&q=80',
        description: 'Unmatched views of the Taj Mahal from every room, reflecting pool courtyards, and Mughal architecture.',
      },
      {
        name: 'Rambagh Palace, Jaipur',
        location: 'Jaipur, Rajasthan',
        tier: 'Historic Royal Residence',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1920&q=80',
        description: 'The former residence of the Maharaja of Jaipur, featuring 47 acres of tranquil gardens and peacock lawns.',
      },
      {
        name: 'Taj Lake Palace, Udaipur',
        location: 'Lake Pichola, Udaipur',
        tier: 'World Heritage Island Palace',
        image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1920&q=80',
        description: 'An 18th-century white marble fantasy floating serenely on Lake Pichola, accessible only by private boat.',
      },
    ],
  },
  {
    id: 'tour-2',
    slug: 'kerala-backwaters-ayurveda-sanctuary',
    destination_id: 'dest-2',
    destination_name: 'Kerala & The Spice Coast',
    title: 'Kerala Sanctuary: Private Houseboats, Spice Hills & Ayurvedic Bliss',
    subtitle: 'Immerse your senses in emerald tea plantations, private backwater cruises, and restorative holistic wellness.',
    duration_days: 8,
    duration_nights: 7,
    price_usd: 3200,
    price_inr: 265000,
    activity_level: 'Leisurely',
    travel_style: 'Spiritual & Wellness',
    group_type: 'Private Wellness Journey',
    is_featured: true,
    hero_image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1920&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1920&q=80',
    ],
    overview:
      'Discover the serene pace of Southern India. Begin among the Dutch and Portuguese colonial avenues of Fort Kochi, journey up into the cool misty cardamom hills of Munnar, glide aboard your private staffed air-conditioned kettuvallam through the Vembanad Lake backwaters, and conclude with three days of customized Ayurvedic rejuvenating therapies at Kumarakom Lake Resort.',
    highlights: [
      '2 nights aboard an exclusive private luxury houseboat with private chef and butler',
      'Doctor-prescribed daily Ayurvedic herbal massages & organic farm-to-table cuisine',
      'Private sunset performance of Kathakali dance and Kalaripayattu martial arts',
      'Exclusive estate tea-tasting session with a third-generation planter in Munnar',
      'Canoe safari into narrow village canals off the tourist path',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Kochi – Ancient Spice Capital',
        location: 'Fort Kochi',
        description:
          'Arrive at Cochin International Airport. Transfer to Brunton Boatyard, a luxury heritage hotel on the harbor. In the late afternoon, take a private harbor cruise to see the historic Chinese Fishing Nets silhouetted against the sunset.',
        stay: 'Brunton Boatyard (Sea Facing Suite)',
        meals: 'Dinner Included',
        highlights: ['Harbor Sunset Cruise', 'Chinese Fishing Nets'],
      },
      {
        day: 2,
        title: 'Colonial Kochi & Classical Art Forms',
        location: 'Fort Kochi',
        description:
          'Explore Mattancherry Palace (Dutch Palace), the 16th-century Jewish Synagogue, and the fragrant spice warehouses of Jew Town. Evening private demonstration of Kathakali costume makeup and storytelling performance.',
        stay: 'Brunton Boatyard',
        meals: 'Breakfast & Lunch',
        highlights: ['Jewish Synagogue & Jew Town', 'Private Kathakali Performance'],
      },
      {
        day: 3,
        title: 'Misty Cardamom & Tea Hills of Munnar',
        location: 'Munnar',
        description:
          'Drive up the scenic Western Ghats past cascading waterfalls and spice plantations to Munnar. Check into Windermere Estate, surrounded by coffee and tea bushes. Enjoy an evening walk through the aromatic cardamom orchards.',
        stay: 'Windermere Estate / Spice Tree Munnar',
        meals: 'Breakfast & Plantation Dinner',
        highlights: ['Western Ghats Scenic Mountain Drive', 'Plantation Walk'],
      },
      {
        day: 4,
        title: 'Tea Masters & Hilltop Panoramic Views',
        location: 'Munnar',
        description:
          'Visit a historic private tea processing factory to understand tea plucking, fermenting, and grading. Sample rare artisanal single-estate white and green teas with a master blender.',
        stay: 'Windermere Estate',
        meals: 'Breakfast & High-Tea',
        highlights: ['Exclusive Tea Tasting', 'Panoramic Ridge Walk'],
      },
      {
        day: 5,
        title: 'Embark on Private Luxury Houseboat Cruise',
        location: 'Alleppey Backwaters',
        description:
          'Descend from the mountains to Alleppey. Step aboard your private luxury kettuvallam crafted with teak and coir. Drift past paddy fields, water lilies, and riverside villages. Your private chef serves freshly caught Karimeen fish and Malabar delicacies.',
        stay: 'Oberoi Vrinda / Luxury Private Houseboat',
        meals: 'All Meals & Refreshments',
        highlights: ['Private Houseboat Boarding', 'Authentic Malabar Feast'],
      },
      {
        day: 6,
        title: 'Kumarakom – Ayurvedic Retreat on the Lake',
        location: 'Kumarakom',
        description:
          'Disembark at Kumarakom Lake Resort, nestled on the banks of Vembanad Lake. Consult with an Ayurvedic Vaidya (doctor) to customize your 2-day wellness and herbal therapy regime.',
        stay: 'Kumarakom Lake Resort (Heritage Villa with Private Pool)',
        meals: 'Breakfast & Ayurvedic Dinner',
        highlights: ['Ayurvedic Doctor Consultation', 'Private Pool Villa'],
      },
      {
        day: 7,
        title: 'Rejuvenation, Yoga & Canoe Safaris',
        location: 'Kumarakom',
        description:
          'Begin with dawn yoga on the lake pier. Indulge in warm herbal oil Abhyanga and Shirodhara treatments. In the afternoon, take a quiet wooden canoe through bird-sanctuary waterways.',
        stay: 'Kumarakom Lake Resort',
        meals: 'All Meals (Wellness Curated)',
        highlights: ['Abhyanga & Shirodhara Treatments', 'Dawn Meditation & Yoga'],
      },
      {
        day: 8,
        title: 'Farewell Kochi & Departure',
        location: 'Cochin Airport',
        description:
          'Leisurely breakfast on the lakefront terrace. Private transfer to Cochin International Airport for your return or onward flight.',
        stay: 'Departure',
        meals: 'Breakfast',
        highlights: ['Airport Transfer & Concierge'],
      },
    ],
    inclusions: [
      '7 nights in premier luxury retreats and private air-conditioned houseboat',
      'Private car and personal chauffeur throughout Kerala',
      'All meals on the private houseboat and wellness dining at Kumarakom',
      'Full Ayurvedic consultation and daily tailored massage therapies',
      'All guided excursions, entrance tickets, and boat transfers',
    ],
    exclusions: [
      'International flights to/from India',
      'Travel insurance and medical coverage',
      'Personal laundry and telephone charges',
    ],
    accommodations: [
      {
        name: 'Brunton Boatyard',
        location: 'Fort Kochi',
        tier: '5-Star Colonial Heritage',
        image: 'https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=1920&q=80',
        description: 'Restored Victorian shipyard hotel overlooking the historic spice harbor.',
      },
      {
        name: 'Luxury Private Kettuvallam',
        location: 'Alleppey Backwaters',
        tier: 'Ultra-Luxury Houseboat',
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1920&q=80',
        description: 'Air-conditioned bedroom suite with private sundeck, personal chef, and dedicated crew.',
      },
      {
        name: 'Kumarakom Lake Resort',
        location: 'Kumarakom, Vembanad Lake',
        tier: 'Luxury Ayurvedic Sanctuary',
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1920&q=80',
        description: 'Heritage pool villas reconstructed from 16th-century traditional Kerala wooden homes.',
      },
    ],
  },
  {
    id: 'tour-3',
    slug: 'ladakh-high-himalayas-expedition',
    destination_id: 'dest-3',
    destination_name: 'Ladakh & High Himalayas',
    title: 'Himalayan High Passes: Glacial Valleys, Monasteries & Luxury Glamping',
    subtitle: 'Venture into the mystical mountain desert of Ladakh, crossing the highest motorable roads on earth.',
    duration_days: 8,
    duration_nights: 7,
    price_usd: 3450,
    price_inr: 285000,
    activity_level: 'Active Adventure',
    travel_style: 'Himalayan Exploration',
    group_type: 'Private Expedition',
    is_featured: true,
    hero_image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1920&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?auto=format&fit=crop&w=1920&q=80',
    ],
    overview:
      'An exhilarating, high-comfort expedition across the Trans-Himalayan desert of Ladakh. Visit ancient 11th-century Buddhist monasteries, sleep in heated luxury geodesic domes in the Nubra Valley, witness the surreal changing colors of high-altitude Pangong Lake at 14,000 feet, and gaze at unpolluted starry constellations through professional optical telescopes.',
    highlights: [
      'Private early morning chant and blessing session with the Rinpoche at Thiksey Gompa',
      'Crossing Khardung La Pass (17,582 ft) and Chang La Pass in customized 4x4 SUVs',
      'Heated luxury nomadic glamping camp in the sand dunes of Hunder',
      'Bactrian double-humped camel safari across high-altitude sand dunes',
      'Professional astrophotography and stargazing session under Bortle Class 1 night skies',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Scenic Himalayan Flight & Acclimatization in Leh',
        location: 'Leh (11,500 ft)',
        description:
          'Fly over the snow-capped Himalayan ranges into Leh. Check into The Grand Dragon Ladakh. Spend the day resting and gently acclimatizing with herbal ginger-honey tea and oxygen-assisted luxury suites.',
        stay: 'The Grand Dragon Ladakh (Royal Suite)',
        meals: 'Dinner Included',
        highlights: ['Himalayan Aerial Views', 'Acclimatization Care'],
      },
      {
        day: 2,
        title: 'Monasteries of the Indus Valley: Thiksey & Hemis',
        location: 'Leh & Indus Valley',
        description:
          'Witness the sunrise prayer ceremony at Thiksey Monastery, reminiscent of Lhasa’s Potala Palace. Tour the treasure museum of Hemis Gompa, followed by an organic Ladakhi lunch at a traditional farm in Stok.',
        stay: 'The Grand Dragon Ladakh',
        meals: 'Breakfast & Farm Lunch',
        highlights: ['Thiksey Morning Chants', 'Hemis Museum'],
      },
      {
        day: 3,
        title: 'Over Khardung La to the Nubra Valley',
        location: 'Khardung La to Nubra Valley',
        description:
          'Ascend through winding mountain switchbacks over Khardung La Pass (17,582 ft). Descend into the dramatic green valley of Nubra where glacial streams meet white sand dunes. Check into Chamba Camp Diskit.',
        stay: 'The Ultimate Travelling Camp (TUTC) / Chamba Camp',
        meals: 'All Meals Included',
        highlights: ['Khardung La Mountain Pass', 'Luxury Glamping Arrival'],
      },
      {
        day: 4,
        title: 'Bactrian Camels & Diskit Monastery',
        location: 'Nubra Valley',
        description:
          'Ride double-humped Bactrian camels across the Hunder sand dunes against a backdrop of snow-capped peaks. Visit the towering 106-foot Maitreya Buddha statue overlooking the valley at Diskit Monastery.',
        stay: 'The Ultimate Travelling Camp / Chamba Camp',
        meals: 'All Meals Included',
        highlights: ['Camel Dunes Ride', '106ft Maitreya Buddha Statue'],
      },
      {
        day: 5,
        title: 'Journey to the Azure Waters of Pangong Tso',
        location: 'Nubra to Pangong Tso (14,270 ft)',
        description:
          'Drive along the wild Shyok River route to Pangong Tso Lake. Marvel as the crystal-clear waters shift through hues of turquoise, cobalt, and emerald. Settle into your heated lakefront luxury dome.',
        stay: 'Merak Luxury Glamping Camp (Heated Lakefront Dome)',
        meals: 'All Meals Included',
        highlights: ['Pangong Tso Turquoise Waters', 'Lakeside Sunset'],
      },
      {
        day: 6,
        title: 'Pangong Sunrise & Return over Chang La to Leh',
        location: 'Pangong to Leh',
        description:
          'Wake early for a magical sunrise reflection over Pangong Lake. Journey back over Chang La Pass (17,590 ft), stopping to visit the 16th-century Chemrey Monastery built into a steep rocky cliff.',
        stay: 'The Grand Dragon Ladakh',
        meals: 'Breakfast & Dinner',
        highlights: ['Pangong Dawn Reflection', 'Chemrey Monastery'],
      },
      {
        day: 7,
        title: 'Leh Old Town, Royal Palace & Farewell Gala',
        location: 'Leh',
        description:
          'Stroll the stone alleys of Old Leh bazaar, visiting local pashmina weavers and Tibetan silversmiths. Enjoy a farewell dinner with traditional Ladakhi folk dance under the stars.',
        stay: 'The Grand Dragon Ladakh',
        meals: 'Breakfast & Farewell Gala Dinner',
        highlights: ['Old Leh Heritage Walk', 'Authentic Ladakhi Folk Gala'],
      },
      {
        day: 8,
        title: 'Departure Flight over the Himalayas',
        location: 'Leh Airport',
        description:
          'Early morning transfer to Kushok Bakula Rimpochee Airport for your mountain flight back to Delhi.',
        stay: 'Departure',
        meals: 'Breakfast',
        highlights: ['Private Airport Transfer'],
      },
    ],
    inclusions: [
      '7 nights in premier luxury hotels and heated glamping dome tents',
      'Private 4x4 Toyota Fortuner with experienced high-altitude Himalayan driver',
      'All meals throughout the expedition (including gourmet field camp meals)',
      'Oxygen cylinders and medical first-responder kit in vehicle',
      'Protected Area Wildlife and Inner Line Permits for Nubra and Pangong',
      'Expert private English-speaking Ladakhi cultural guide',
    ],
    exclusions: [
      'International flights to/from India',
      'Personal thermal outerwear (available for rent)',
      'Travel and high-altitude emergency insurance',
    ],
    accommodations: [
      {
        name: 'The Grand Dragon Ladakh',
        location: 'Leh',
        tier: '5-Star Luxury Mountain Hotel',
        image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1920&q=80',
        description: 'Solar-heated luxury hotel with oxygen-enriched suites and views of the Stok Kangri mountain range.',
      },
      {
        name: 'Chamba Camp Diskit (TUTC)',
        location: 'Nubra Valley',
        tier: 'Ultra-Luxury Mobile Glamping',
        image: 'https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?auto=format&fit=crop&w=1920&q=80',
        description: 'Colonial-style heated safari tents with private butler service and four-poster beds.',
      },
    ],
  },
  {
    id: 'tour-4',
    slug: 'royal-bengal-tiger-safari',
    destination_id: 'dest-5',
    destination_name: 'Ranthambore & Royal Wilds',
    title: 'The Sovereign Wild: Royal Bengal Tiger Safari & Jungle Lodges',
    subtitle: 'Exclusive private game drives in Ranthambore & Bandhavgarh with India’s foremost naturalists.',
    duration_days: 7,
    duration_nights: 6,
    price_usd: 3600,
    price_inr: 298000,
    activity_level: 'Moderate',
    travel_style: 'Wildlife Safari',
    group_type: 'Private Safari Expedition',
    is_featured: true,
    hero_image: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1920&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1562183667-a159d28118ec?auto=format&fit=crop&w=1920&q=80',
    ],
    overview:
      'Track the elusive Royal Bengal Tiger through the ancient ruins, watering holes, and deciduous jungles of India’s premier national parks. Travel in private open-top 4x4 safari jeeps accompanied by master trackers. Relax in the opulent grandeur of Aman-i-Khás and The Oberoi Vanyavilas.',
    highlights: [
      '6 private exclusive jeep safaris in premier core zones (Zones 1-5)',
      'Stay at Aman-i-Khás luxury tented camp with private butler (batman)',
      'Sunset bush dinners under the canopy with natural history lectures',
      'Visit the 10th-century Ranthambore Fort perched above tiger territory',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Delhi to Ranthambore – Arrival in the Kingdom of the Tiger',
        location: 'Delhi to Ranthambore',
        description:
          'Transfer via private executive train or luxury chauffeur car from Delhi to Sawai Madhopur. Arrive at The Oberoi Vanyavilas. Unwind in your royal tented villa with private garden.',
        stay: 'The Oberoi Vanyavilas / Aman-i-Khás',
        meals: 'Dinner Included',
        highlights: ['Private Executive Transfer', 'Royal Safari Tent Arrival'],
      },
      {
        day: 2,
        title: 'Dawn & Afternoon Core Zone Tiger Safaris',
        location: 'Ranthambore National Park',
        description:
          'Embark on your first private dawn safari into the core tiger zones. Track pugmarks and listen to deer alarm calls. Return for a gourmet poolside lunch, followed by an afternoon game drive.',
        stay: 'The Oberoi Vanyavilas',
        meals: 'All Meals Included',
        highlights: ['Dawn & Dusk Game Drives', 'Bengal Tiger Tracking'],
      },
      {
        day: 3,
        title: 'Ranthambore Fort & Medieval Jungle Lakes',
        location: 'Ranthambore',
        description:
          'Morning safari along the picturesque Padam Talao and Rajbagh lake ruins. In the afternoon, ascend the massive 10th-century UNESCO Ranthambore Fort overlooking the jungle.',
        stay: 'The Oberoi Vanyavilas',
        meals: 'All Meals Included',
        highlights: ['Jungle Lakes Safari', 'UNESCO Ranthambore Fort Walk'],
      },
      {
        day: 4,
        title: 'Deep Forest Tracking & Birdlife Sanctuaries',
        location: 'Ranthambore',
        description:
          'Explore different ecological habitats seeking leopards, sloth bears, marsh crocodiles, and rare birds of prey with your senior naturalist.',
        stay: 'The Oberoi Vanyavilas',
        meals: 'All Meals Included',
        highlights: ['Leopard & Sloth Bear Tracking', 'Private Wildlife Lecture'],
      },
      {
        day: 5,
        title: 'Village Craft Walk & Evening Stargazing Bush Dinner',
        location: 'Ranthambore',
        description:
          'Visit a local women’s embroidery artisan cooperative supporting wildlife conservation. Conclude with an enchanting bush dinner illuminated by bonfire and hurricane lanterns.',
        stay: 'The Oberoi Vanyavilas',
        meals: 'All Meals Included',
        highlights: ['Conservation Artisan Visit', 'Lantern Bush Dinner'],
      },
      {
        day: 6,
        title: 'Final Morning Safari & Leisurely Afternoon',
        location: 'Ranthambore',
        description:
          'Final morning game drive through the forest canopy. Spend the afternoon indulging in signature Ayurvedic spa therapies and private high-tea on the observation tower.',
        stay: 'The Oberoi Vanyavilas',
        meals: 'All Meals Included',
        highlights: ['Final Morning Safari', 'Observation Tower High-Tea'],
      },
      {
        day: 7,
        title: 'Return to Delhi & International Departure',
        location: 'Ranthambore to Delhi',
        description:
          'Morning private transfer back to Delhi International Airport for your connecting flight home.',
        stay: 'Departure',
        meals: 'Breakfast',
        highlights: ['Private Chauffeur Return Transfer'],
      },
    ],
    inclusions: [
      '6 nights in premier 5-star luxury tented villas (Oberoi Vanyavilas / Aman-i-Khás)',
      '6 private exclusive 4x4 safari game drives with expert senior naturalists',
      'All meals, soft beverages, and curated bush dining experiences',
      'All national park conservation permits and VIP guide allocations',
      'Private transfers to and from Delhi',
    ],
    exclusions: ['International airfare', 'Gratuities for naturalists and trackers', 'Personal insurance'],
    accommodations: [
      {
        name: 'The Oberoi Vanyavilas',
        location: 'Ranthambore',
        tier: '5-Star Luxury Jungle Resort',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1920&q=80',
        description: 'Triple-canopied luxury tents with teakwood floors, clawfoot baths, and private walled gardens.',
      },
    ],
  },
  {
    id: 'tour-5',
    slug: 'spiritual-ganges-varanasi-odyssey',
    destination_id: 'dest-4',
    destination_name: 'Varanasi & Sacred Ganges',
    title: 'Ganges Illumination: Varanasi, Sarnath & The Golden Temple',
    subtitle: 'A transformative spiritual and cultural pilgrimage through India’s oldest sacred cities.',
    duration_days: 6,
    duration_nights: 5,
    price_usd: 2450,
    price_inr: 205000,
    activity_level: 'Leisurely',
    travel_style: 'Spiritual & Wellness',
    group_type: 'Private Cultural Tour',
    is_featured: false,
    hero_image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1920&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1612865547334-09cb8cb455da?auto=format&fit=crop&w=1920&q=80',
    ],
    overview:
      'Immerse yourself in 3,000 years of living spirituality along the sacred River Ganges. From dawn prayers on silent wooden boats to the vibrant evening Aarti flame ceremony and the tranquil deer parks of Sarnath.',
    highlights: [
      'Private dawn and twilight wooden boat cruises on the sacred River Ganges',
      'VIP front-row seating for the Ganga Aarti ceremony at Dashashwamedh Ghat',
      'Guided meditation session with a Buddhist monk in Sarnath',
      'Stay at BrijRama Palace — an 18th-century stone palace directly on the ghats',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Varanasi & Heritage Palace Check-in',
        location: 'Varanasi',
        description:
          'Arrive at Lal Bahadur Shastri Airport. Board a private vintage boat to approach BrijRama Palace from the river. Witness the timeless skyline of minarets and temple spires.',
        stay: 'BrijRama Palace (Ghat View Suite)',
        meals: 'Dinner Included',
        highlights: ['Riverboat Palace Arrival'],
      },
      {
        day: 2,
        title: 'Dawn Rowing & Historic Ghats Walking Tour',
        location: 'Varanasi',
        description:
          'Glide across the Ganges at sunrise as pilgrims perform ancient prayers. Walk through the ancient galis (alleys) visiting centuries-old sweet shops and silk looms.',
        stay: 'BrijRama Palace',
        meals: 'Breakfast & Lunch',
        highlights: ['Dawn Ganges Rowing', 'Historic Old Town Alley Exploration'],
      },
      {
        day: 3,
        title: 'Sarnath – Where Buddhism Was Born',
        location: 'Sarnath',
        description:
          'Visit the peaceful deer park and Dhamek Stupa in Sarnath, where Buddha delivered his first sermon. Meet with a Buddhist master for private meditation.',
        stay: 'BrijRama Palace',
        meals: 'Breakfast & High-Tea',
        highlights: ['Sarnath Dhamek Stupa', 'Monk Meditation Session'],
      },
      {
        day: 4,
        title: 'Sacred Temples & Evening Ganga Aarti Spectacle',
        location: 'Varanasi',
        description:
          'Visit the Kashi Vishwanath Temple corridor. In the evening, take a private boat to Dashashwamedh Ghat for the world-famous Ganga Aarti ritual of chanting and fire offerings.',
        stay: 'BrijRama Palace',
        meals: 'Breakfast & Gala Dinner',
        highlights: ['Kashi Vishwanath Corridor', 'VIP Ganga Aarti Boat View'],
      },
      {
        day: 5,
        title: 'Artisan Weavers & Culinary Traditions',
        location: 'Varanasi',
        description:
          'Explore traditional master silk-weaving ateliers creating regal Benarasi brocades with real gold and silver threads. Enjoy an afternoon royal thali feast.',
        stay: 'BrijRama Palace',
        meals: 'Breakfast & Royal Thali',
        highlights: ['Benarasi Silk Weaving Masterclass'],
      },
      {
        day: 6,
        title: 'Final Blessing & Departure',
        location: 'Varanasi Airport',
        description:
          'Farewell morning boat ride and transfer to the airport for your onward domestic flight.',
        stay: 'Departure',
        meals: 'Breakfast',
        highlights: ['Airport Transfer'],
      },
    ],
    inclusions: [
      '5 nights at BrijRama Palace (Ghat View Heritage Suite)',
      'All private boat excursions with expert historian guides',
      'Daily breakfast and curated culinary experiences',
      'VIP temple and Aarti arrangements',
      'Private airport transfers',
    ],
    exclusions: ['International & domestic airfare', 'Discretionary tips and personal expenses'],
    accommodations: [
      {
        name: 'BrijRama Palace',
        location: 'Darbhanga Ghat, Varanasi',
        tier: '5-Star Heritage Palace on the Ghats',
        image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1920&q=80',
        description: 'One of the oldest stone palaces in Varanasi, perched right over the sacred Ganges.',
      },
    ],
  },
  {
    id: 'tour-6',
    slug: 'coastal-goa-portuguese-villas',
    destination_id: 'dest-6',
    destination_name: 'Goa & The Portuguese Heritage Coast',
    title: 'Goan Grandeur: Private Catamarans, Latin Quarters & Heritage Stays',
    subtitle: 'Experience the refined aristocratic side of Goa with private yachts, boutique villas, and haute cuisine.',
    duration_days: 6,
    duration_nights: 5,
    price_usd: 2850,
    price_inr: 235000,
    activity_level: 'Leisurely',
    travel_style: 'Coastal & Luxury Stays',
    group_type: 'Private Coastal Getaway',
    is_featured: false,
    hero_image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1920&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1920&q=80',
      'https://images.unsplash.com/photo-1587922546307-776227941871?auto=format&fit=crop&w=1920&q=80',
    ],
    overview:
      'Discover Goa beyond the ordinary. Stay in restored 18th-century Portuguese estates, sail private catamarans along secluded estuaries, savor private tasting menus from award-winning chefs, and stroll through UNESCO-listed Old Goa churches.',
    highlights: [
      'Private sunset catamaran charter with champagne along the Arabian coastline',
      'Exclusive architectural walk in Fontainhas Latin Quarter with a heritage conservationist',
      '5-course Indo-Portuguese seafood tasting menu paired with artisanal spirits',
      'Stay in secluded 5-star private beach villas at Ahilya by the Sea',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Goa – The Coastal Welcome',
        location: 'Goa',
        description:
          'Chauffeur transfer from Goa International Airport to Ahilya by the Sea. Relax by the oceanfront infinity pool overlooking Dolphin Bay.',
        stay: 'Ahilya by the Sea / The Leela Goa',
        meals: 'Dinner Included',
        highlights: ['Private Airport Transfer', 'Oceanfront Welcome Dinner'],
      },
      {
        day: 2,
        title: 'Latin Quarter Heritage & Portuguese Mansions',
        location: 'Panaji & Fontainhas',
        description:
          'Stroll the pastel-colored alleys of Fontainhas. Visit the 400-year-old Casa Araujo Alvares mansion and enjoy lunch with a Goan noble family.',
        stay: 'Ahilya by the Sea',
        meals: 'Breakfast & Heritage Lunch',
        highlights: ['Fontainhas Architecture', 'Private Mansion High-Tea'],
      },
      {
        day: 3,
        title: 'Private Catamaran Charter on the Arabian Sea',
        location: 'Arabian Sea',
        description:
          'Board your private luxury 45-foot catamaran. Sail past historic Aguada Fort, anchor in a secluded bay for swimming and paddleboarding, followed by sunset champagne.',
        stay: 'Ahilya by the Sea',
        meals: 'Breakfast & Seafood Barbecue on Boat',
        highlights: ['Private Catamaran Sail', 'Secluded Cove Swimming'],
      },
      {
        day: 4,
        title: 'Churches of Old Goa & Spice Plantation Feast',
        location: 'Old Goa',
        description:
          'Tour the Basilica of Bom Jesus and Se Cathedral. Visit an organic spice plantation for a traditional feast served on banana leaves.',
        stay: 'Ahilya by the Sea',
        meals: 'Breakfast & Spice Farm Feast',
        highlights: ['UNESCO Basilica of Bom Jesus', 'Organic Spice Farm'],
      },
      {
        day: 5,
        title: 'Private Wellness & Farewell Seaside Dinner',
        location: 'Goa',
        description:
          'Day at leisure for spa treatments, private yoga, or beach relaxation. Conclude with a romantic 5-course beachfront dinner under the stars.',
        stay: 'Ahilya by the Sea',
        meals: 'Breakfast & 5-Course Farewell Gala',
        highlights: ['Beachfront Farewell Dinner'],
      },
      {
        day: 6,
        title: 'Departure from Goa',
        location: 'Goa Airport',
        description:
          'Leisurely breakfast before your private chauffeur transfer to the airport for your onward journey.',
        stay: 'Departure',
        meals: 'Breakfast',
        highlights: ['Airport Concierge Transfer'],
      },
    ],
    inclusions: [
      '5 nights luxury seaside villa accommodation',
      'Private catamaran sunset charter with champagne and chef on board',
      'Private air-conditioned car and chauffeur throughout',
      'All curated heritage tours and culinary experiences',
    ],
    exclusions: ['Airfare', 'Personal purchases and spa therapies'],
    accommodations: [
      {
        name: 'Ahilya by the Sea',
        location: 'Nerul, Goa',
        tier: '5-Star Boutique Seaside Estate',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1920&q=80',
        description: 'Tucked away in a quiet corner of Dolphin Bay, offering refined elegance and sea-facing pools.',
      },
    ],
  },
];
